%MAIN_MONTH4A_CASE_STUDIES
%Thesis roadmap Month 4, item I: case studies quantifying cost, emissions,
%and reliability improvements from the energy hub / multi-timescale approach.
%
%   Four cases, each isolating one specific modeling contribution from
%   the rest of this project, so the improvement from each can be
%   attributed rather than only shown in aggregate:
%
%     Case 1 "Conventional"        : no PV/FC/heat pump/storage at all --
%                                     grid electricity + gas boiler heat.
%                                     The pre-energy-hub reference point.
%     Case 2 "Day-ahead only"      : the energy hub exists and is
%                                     scheduled by the day-ahead LP, but
%                                     executed OPEN LOOP -- no intraday/
%                                     real-time correction. Isolates the
%                                     value of the rolling multi-timescale
%                                     coordination layers.
%     Case 3 "No robust reserve"   : full closed-loop day-ahead+intraday+
%                                     real-time, but the day-ahead reserve
%                                     margin is disabled (reserveScale=0).
%                                     Isolates the value of the robustness
%                                     proxy.
%     Case 4 "Full proposed system": everything as built (robust day-ahead
%                                     + rolling intraday/real-time), the
%                                     complete approach this thesis proposes.
%     Case 5 "Constant efficiency"  : NOT part of the Case 1-4 progression
%                                     (it isolates PWL itself, not a
%                                     coordination/robustness layer) --
%                                     full Case-4-style closed loop, but
%                                     the PLANNING stack (day-ahead +
%                                     intraday) believes the fuel cell has
%                                     ONE constant efficiency instead of
%                                     the true nonlinear PWL curve
%                                     (opts.usePWL=false in
%                                     simulate_multiscale_day.m). The
%                                     physical realization always uses
%                                     the TRUE curve regardless -- the
%                                     fuel cell doesn't know what the
%                                     planner assumed about it -- so a
%                                     WRONG planning model can plan one
%                                     cost and realize a different one.
%                                     Run at BOTH DOE 2026 target prices
%                                     (H2_doeTargetDelivered $2.93/kg,
%                                     the like-for-like headline, and
%                                     H2_doeTargetGate $2.00/kg, an
%                                     optimistic bound -- see the three
%                                     named scenarios and the
%                                     production-vs-delivered
%                                     distinction in
%                                     multiscale_default_params.m), not
%                                     the H2_today default ($0.22/kWh =
%                                     $7.33/kg) that Cases 1-4 use. Those
%                                     are the scenarios in which the fuel
%                                     cell is economic at all: at today's
%                                     delivered cost it never dispatches
%                                     (confirmed across every
%                                     seed/uncertainty combination used
%                                     elsewhere in this project), so a
%                                     PWL-vs-constant comparison there
%                                     would be vacuous -- 0 fuel either
%                                     way, nothing measured. Asking what
%                                     the fuel cell's part-load model is
%                                     worth is only meaningful where the
%                                     fuel cell runs.
%                                     KEY RESULT: the PWL cost benefit is
%                                     UTILIZATION-DEPENDENT -- constant
%                                     efficiency costs ~0.20% more at the
%                                     delivered price (138 kWh fuel) but
%                                     ~1.47% more at the gate price (339
%                                     kWh), so it is reported as a range
%                                     rather than a single figure. The
%                                     cost-independent argument is
%                                     stronger: without the fill-order
%                                     binaries the LP produces a
%                                     physically impossible dispatch at
%                                     ANY price.
%                                     Cases 1-4 above are untouched and
%                                     keep the shared default p.
%
%   Reliability is checked against a SHARED feeder capacity limit
%   (p.reliability.feederCapMargin x Case 4's own day-ahead peak import
%   -- i.e. "the connection sized for the proposed system"), applied to
%   cases 2-4 so the comparison isolates coordination/robustness, not
%   different infrastructure sizing. Case 1 has no such cap (a
%   conventional system is simply sized for its own peak) but its much
%   higher peak import is reported as its own finding: the energy hub
%   materially reduces how large a grid connection is needed at all.
%
%   Depends on Month 3's dispatch stack (../month3_multiscale_optimization).
%
%   Run with:  main_month4a_case_studies

clear; clc;
addpath('../month3_multiscale_optimization');

p = multiscale_default_params();
fc = forecast_profiles(42);

fprintf('=====================================================\n');
fprintf(' Case studies: cost, emissions, reliability\n');
fprintf('=====================================================\n');

fprintf('\nRunning Case 1 (conventional: grid + gas boiler, no energy hub)...\n');
C1 = simulate_conventional_baseline(p, fc);

fprintf('Running Case 2 (energy hub, day-ahead only, open loop)...\n');
C2 = simulate_multiscale_day(p, fc, struct('useIntraday', false, 'reserveScale', 1.0));

fprintf('Running Case 3 (energy hub, full rolling dispatch, no robust reserve)...\n');
C3 = simulate_multiscale_day(p, fc, struct('useIntraday', true, 'reserveScale', 0.0));

fprintf('Running Case 4 (energy hub, full proposed system)...\n');
C4 = simulate_multiscale_day(p, fc, struct('useIntraday', true, 'reserveScale', 1.0));

% Reliability threshold. feeder_capacity.m is consumed ONLY by
% reliability_check below, AFTER every case has been simulated -- it never
% enters simulate_multiscale_day or any dispatch constraint, so the choice
% of basis cannot move any case's cost, CO2 or peak. It can only move
% unmetE and violHrs. Both bases are computed so the reader can see whether
% the Case 4 advantage survives a threshold Case 4 did not define.
[feederCap, capLabel]         = feeder_capacity(p, fc, 'design');
[feederCapC4, capLabelC4]     = feeder_capacity(p, fc, 'case4', C4.dayaheadPeakImport);
fprintf('\nFeeder capacity, DEFAULT basis : %.2f kW  [%s]\n', feederCap, capLabel);
fprintf('Feeder capacity, comparison basis: %.2f kW  [%s]\n', feederCapC4, capLabelC4);

V2 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, feederCap);
V3 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, feederCap);
V4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, feederCap);

V2c4 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, feederCapC4);
V3c4 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, feederCapC4);
V4c4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, feederCapC4);

cases = {'1: Conventional', '2: Day-ahead only', '3: No robust reserve', '4: Full proposed'};
cost = [C1.actualCost, C2.actualCost, C3.actualCost, C4.actualCost];
emis = [C1.emissions_kgCO2, C2.emissions_kgCO2, C3.emissions_kgCO2, C4.emissions_kgCO2];
peak = [C1.dayaheadPeakImport, max(C2.Pg_imp5), max(C3.Pg_imp5), max(C4.Pg_imp5)];
unmetE = [NaN, V2.unmetEnergy_kWh, V3.unmetEnergy_kWh, V4.unmetEnergy_kWh];
violHrs = [NaN, V2.violationHours, V3.violationHours, V4.violationHours];

fprintf('\n%-24s %10s %12s %10s %14s %12s\n', 'Case', 'Cost($)', 'CO2(kg)', 'Peak(kW)', 'UnmetE(kWh)', 'ViolHrs');
for i = 1:4
    if isnan(unmetE(i))
        fprintf('%-24s %10.2f %12.1f %10.1f %14s %12s\n', cases{i}, cost(i), emis(i), peak(i), 'n/a', 'n/a');
    else
        fprintf('%-24s %10.2f %12.1f %10.1f %14.2f %12.2f\n', cases{i}, cost(i), emis(i), peak(i), unmetE(i), violHrs(i));
    end
end

%% Reliability under both threshold bases -----------------------------
fprintf('\n--- Reliability under BOTH capacity bases (cost/CO2/peak unaffected) ---\n');
fprintf('The reliability threshold is the one metric whose basis is a methodological\n');
fprintf('choice, so both are shown. Cost, CO2 and peak above cannot move with it:\n');
fprintf('feeder_capacity.m feeds only reliability_check.m, after all cases are solved.\n\n');
fprintf('%-24s %11s %10s   %11s %10s\n', '', 'design', '', 'case4-derived', '');
fprintf('%-24s %11s %10s   %11s %10s\n', 'Case', 'UnmetE', 'ViolHrs', 'UnmetE', 'ViolHrs');
relNames = {'2: Day-ahead only', '3: No robust reserve', '4: Full proposed'};
Vd = {V2, V3, V4}; Vc = {V2c4, V3c4, V4c4};
for i = 1:3
    fprintf('%-24s %11.2f %10.2f   %11.2f %10.2f\n', relNames{i}, ...
        Vd{i}.unmetEnergy_kWh, Vd{i}.violationHours, ...
        Vc{i}.unmetEnergy_kWh, Vc{i}.violationHours);
end

%% Threshold sensitivity ----------------------------------------------
% The three cases' realized peaks differ by under 2 kW, so the binary
% "violations vs. no violations" verdict is inherently threshold-sensitive.
% Sweep it rather than assert a single number.
fprintf('\n--- Threshold sensitivity (violation hours; realized peaks C2/C3/C4 = %.2f/%.2f/%.2f kW) ---\n', ...
    max(C2.Pg_imp5), max(C3.Pg_imp5), max(C4.Pg_imp5));
capSweep = [90 95 100 feederCap feederCapC4 106 110];
capSweep = sort(unique(round(capSweep*100)/100));
fprintf('%10s %10s %10s %10s   %s\n', 'cap(kW)', 'C2', 'C3', 'C4', 'unmetE C2/C3/C4 (kWh)');
for cc = capSweep
    v2 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, cc);
    v3 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, cc);
    v4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, cc);
    fprintf('%10.2f %10.2f %10.2f %10.2f   %.2f / %.2f / %.2f\n', cc, ...
        v2.violationHours, v3.violationHours, v4.violationHours, ...
        v2.unmetEnergy_kWh, v3.unmetEnergy_kWh, v4.unmetEnergy_kWh);
end

if V4.violationHours < min(V2.violationHours, V3.violationHours)
    survives = 'YES';
else
    survives = 'NO';
end
% Exact window in which Case 4 is the ONLY case inside the limit:
% caps >= Case 4's own peak but below the next-lowest peak.
pk4      = max(C4.Pg_imp5);
pkOthers = min(max(C2.Pg_imp5), max(C3.Pg_imp5));
pkAll    = max(max(C2.Pg_imp5), max(C3.Pg_imp5));
pkSpread = pkAll - pk4;
fprintf(['\nDoes Case 4''s reliability advantage survive an independently-set threshold? %s.\n' ...
    'Under the design-basis cap (%.2f kW, built only from load and nameplate ratings --\n' ...
    'no dispatch strategy involved) Case 4 still records %.2f violation hours against\n' ...
    '%.2f and %.2f for Cases 2 and 3.\n' ...
    '\nBut the sweep above shows how NARROW that verdict is, and this qualification\n' ...
    'belongs with the result: the three cases'' realized peaks lie within %.2f kW of each\n' ...
    'other, so Case 4 is the ONLY case inside the limit just for caps in [%.2f, %.2f) kW\n' ...
    '-- a window %.2f kW wide, about %.1f%% of the peak itself. Set the cap below %.2f kW\n' ...
    'and Case 4 violates too; set it at or above %.2f kW and NONE of them violate. The\n' ...
    'binary "zero violations" headline is therefore an artifact of where the line is\n' ...
    'drawn, and should not be quoted on its own.\n' ...
    '\nIn fairness the design cap (%.2f kW) does land inside that narrow window, and it\n' ...
    'is only fair to flag that rather than let it pass: the diversity factor (%.2f) was\n' ...
    'chosen from the load composition -- few large controllable loads, so high\n' ...
    'coincidence -- and NOT reverse-engineered from the answer, but a lower factor would\n' ...
    'change the verdict. At 0.75-0.80 the cap falls to roughly 92-98 kW and, as the sweep\n' ...
    'shows, ALL THREE cases then violate. The reader should treat "Case 4 alone is clean"\n' ...
    'as conditional on a connection contracted tightly around the system''s own peak.\n' ...
    '\nWhat IS robust is the ORDERING of unmet energy: at every cap in the sweep where\n' ...
    'anything violates at all, Case 4 has the lowest unmet energy and Case 3 (no robust\n' ...
    'reserve) the highest -- including at 90 and 95 kW, where all three breach the limit\n' ...
    'and the binary violation count no longer separates them at all. That ranking holds\n' ...
    'across the whole range rather than at one threshold, so it -- not the zero -- is the\n' ...
    'defensible reliability claim.\n'], ...
    survives, feederCap, V4.violationHours, V2.violationHours, V3.violationHours, ...
    pkSpread, pk4, pkOthers, pkOthers - pk4, 100*(pkOthers - pk4)/pk4, pk4, pkAll, ...
    feederCap, p.reliability.diversityFactor);

fprintf('\n--- Improvements relative to Case 1 (conventional) ---\n');
fprintf('Case 4 cost reduction: %.1f%%\n', 100*(cost(1)-cost(4))/cost(1));
fprintf('Case 4 CO2 reduction:  %.1f%%\n', 100*(emis(1)-emis(4))/emis(1));
fprintf(['\nWHAT THESE TWO NUMBERS DO AND DO NOT MEASURE -- read before quoting them.\n' ...
    'They compare a system WITH PV, battery, EV and heat pump against one with NONE of\n' ...
    'them: Case 1 is grid import plus a gas boiler and has no PV at all, while Case 4\n' ...
    'has %.0f kWh/day of free solar. Most of the %.1f%% is therefore the value of OWNING\n' ...
    'THE EQUIPMENT, not the value of the energy-hub modelling this thesis contributes.\n' ...
    'Any competently dispatched system with the same hardware would capture most of it.\n' ...
    'Quoting %.1f%% as a result of the modelling work would be a category error, and it\n' ...
    'should never be cited without saying what it compares.\n' ...
    '\nThe numbers that DO isolate this thesis''s own contributions are the ablations\n' ...
    'below and Case 5, and they are appropriately smaller:\n' ...
    '  rolling intraday/real-time layers  Case 2 vs 4\n' ...
    '  robust reserve margin              Case 3 vs 4\n' ...
    '  PWL vs constant efficiency         Case 5 (0.20%%-1.47%%, utilization-dependent)\n' ...
    'Those are the defensible claims for the modelling. The %.1f%% belongs in a sentence\n' ...
    'about electrification and on-site generation, not about optimization.\n'], ...
    sum(C4.DA.Ps), 100*(cost(1)-cost(4))/cost(1), 100*(cost(1)-cost(4))/cost(1), ...
    100*(cost(1)-cost(4))/cost(1));
fprintf(['Peak grid import: Case 1 = %.1f kW vs. Case 4 = %.1f kW -- NOT a reduction.\n' ...
    'Case 4 serves strictly more than Case 1 (EV fleet charging, heat-pump electrification\n' ...
    'of what was gas heat in Case 1), and its day-ahead LP deliberately imports MORE than\n' ...
    'instantaneous need during cheap overnight hours to pre-charge storage for later --\n' ...
    'a real, honest finding: cost/emission optimality and peak-shaving are different\n' ...
    'objectives, and this system was optimized for the former. A peak-shaving objective\n' ...
    '(or a demand charge in the price signal) would need to be added explicitly to also\n' ...
    'control for the latter -- it does not fall out of energy-cost minimization alone.\n'], peak(1), peak(4));

fprintf('\n--- Value of each contribution (relative to the FULL Case 4) ---\n');
fprintf('Removing intraday/real-time correction (Case 2 vs 4): cost %+.1f%%, unmet energy %+.2f kWh, violations %+.2f h\n', ...
    100*(cost(2)-cost(4))/cost(4), unmetE(2)-unmetE(4), violHrs(2)-violHrs(4));
fprintf('Removing the robust reserve margin (Case 3 vs 4):     cost %+.1f%%, unmet energy %+.2f kWh, violations %+.2f h\n', ...
    100*(cost(3)-cost(4))/cost(4), unmetE(3)-unmetE(4), violHrs(3)-violHrs(4));

%% Case 5: PWL vs. constant fuel cell efficiency (isolates PWL itself) ------
fprintf('\n=====================================================\n');
fprintf(' Case 5: PWL vs. constant fuel cell efficiency\n');
fprintf('=====================================================\n');
fprintf(['Run at BOTH DOE 2026 target prices, not the H2_today default ($%.2f/kWh =\n' ...
    '$%.2f/kg) used by Cases 1-4. At today''s delivered cost the fuel cell never\n' ...
    'dispatches, so a PWL-vs-constant comparison there would weigh 0 fuel against 0\n' ...
    'fuel and measure nothing -- what a part-load model is worth is only a meaningful\n' ...
    'question where the component actually runs. The two target prices differ in COST\n' ...
    'BASIS (see multiscale_default_params.m):\n' ...
    '  H2_doeTargetDelivered  $%.4f/kWh = $%.2f/kg -- DOE''s 2026 PRODUCTION target\n' ...
    '        carried to the meter with this project''s own delivery markup (%.3fx).\n' ...
    '        LIKE-FOR-LIKE against H2_today; read this as the headline.\n' ...
    '  H2_doeTargetGate       $%.4f/kWh = $%.2f/kg -- the same target at the\n' ...
    '        production gate, unmodified. OPTIMISTIC BOUND (delivery assumed free).\n' ...
    'Cases 1-4 above are untouched.\n'], ...
    p.scenarios.H2_today, p.scenarios.H2_today*p.scenarios.H2_kWhPerKg, ...
    p.scenarios.H2_doeTargetDelivered, p.scenarios.H2_doeTargetDelivered*p.scenarios.H2_kWhPerKg, ...
    p.scenarios.H2_deliveryMarkup, ...
    p.scenarios.H2_doeTargetGate, p.scenarios.H2_doeTargetGate*p.scenarios.H2_kWhPerKg);

% p5 stays on the GATE price: the detailed Optimism diagnostic and its
% explanation further below are anchored to that run.
p5 = p;
p5.price_H2 = p.scenarios.H2_doeTargetGate;
p5del = p;
p5del.price_H2 = p.scenarios.H2_doeTargetDelivered;

fprintf('\nRunning Case 5 at the DELIVERED target (like-for-like)...\n');
C5pwlDel   = simulate_multiscale_day(p5del, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', true));
C5constDel = simulate_multiscale_day(p5del, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', false));

fprintf('Running Case 5 at the GATE target (optimistic bound)...\n');
C5pwl   = simulate_multiscale_day(p5, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', true));
C5const = simulate_multiscale_day(p5, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', false));

V5pwl   = reliability_check(C5pwl.Pg_imp5,   C5pwl.Pg_exp5,   feederCap);
V5const = reliability_check(C5const.Pg_imp5, C5const.Pg_exp5, feederCap);

%% Headline: the PWL benefit scales with fuel-cell utilization ---------
relDel  = 100*(C5constDel.actualCost - C5pwlDel.actualCost)/abs(C5pwlDel.actualCost);
relGate = 100*(C5const.actualCost    - C5pwl.actualCost)   /abs(C5pwl.actualCost);
fuelDel  = sum(C5pwlDel.DA.PH2);   hrsDel  = sum(C5pwlDel.DA.PH2 > 1e-6);
fuelGate = sum(C5pwl.DA.PH2);      hrsGate = sum(C5pwl.DA.PH2 > 1e-6);

fprintf('\n%-26s %14s %14s %14s %12s\n', 'Hydrogen price', 'FC fuel(kWh)', 'PWL($)', 'const($)', 'const vs PWL');
fprintf('%-26s %14.1f %14.4f %14.4f %11.2f%%\n', ...
    sprintf('$%.2f/kg delivered', p5del.price_H2*p.scenarios.H2_kWhPerKg), ...
    fuelDel, C5pwlDel.actualCost, C5constDel.actualCost, relDel);
fprintf('%-26s %14.1f %14.4f %14.4f %11.2f%%\n', ...
    sprintf('$%.2f/kg gate', p5.price_H2*p.scenarios.H2_kWhPerKg), ...
    fuelGate, C5pwl.actualCost, C5const.actualCost, relGate);

fprintf(['\nTHE PWL COST BENEFIT IS UTILIZATION-DEPENDENT, and this must be read as a range,\n' ...
    'not a single number. Modelling the fuel cell with a constant efficiency instead of\n' ...
    'PWL costs %.2f%% more at the like-for-like DELIVERED price (%.0f kWh of fuel over %d\n' ...
    'hours) but %.2f%% more at the optimistic GATE price (%.0f kWh over %d hours). The\n' ...
    'mechanism is not subtle: a part-load model can only matter in proportion to how much\n' ...
    'energy actually flows through the nonlinear device, and %.1fx more fuel flows at the\n' ...
    'gate price. Quoting %.2f%% alone would be quietly conditioned on the more optimistic\n' ...
    'of the two cost bases, so both are reported. On the like-for-like basis the cost\n' ...
    'benefit is real but modest -- %.2f%% is a smaller claim than %.2f%%, and stating that\n' ...
    'plainly is the point.\n' ...
    '\nTHE VALIDITY ARGUMENT DOES NOT DEPEND ON COST AT ALL, and is the stronger one. The\n' ...
    'PWL segments and fill-order binaries exist to keep the dispatch PHYSICALLY POSSIBLE,\n' ...
    'not to save money. Without the ordering binaries the LP relaxation fills segment 2\n' ...
    'while segment 1 is still only fractionally full (verified counterfactual: PH2seg(2)\n' ...
    '> 0 at PH2seg(1) = 4.576 of 30), which reports more electricity per unit hydrogen\n' ...
    'than the device can physically produce. That defect exists at EVERY price, including\n' ...
    'ones where the cost difference rounds to zero. A model that violates the machine it\n' ...
    'describes is wrong irrespective of what the error happens to cost on a given day --\n' ...
    'so the case for the PWL/MILP formulation rests on correctness first and economics\n' ...
    'second.\n'], ...
    relDel, fuelDel, hrsDel, relGate, fuelGate, hrsGate, ...
    fuelGate/fuelDel, relGate, relDel, relGate);

fprintf(['\nThe detailed diagnostic below is for the GATE run (the higher-throughput case,\n' ...
    'where the modeling effect is clearest).\n']);

% OPTIMISM DIAGNOSTIC: does the planning model over- or under-state what the
% fuel cell actually delivers, over the fuel levels it actually dispatched?
% Fuel-weighted over the whole day (total electricity the planner believed its
% own committed fuel would produce, minus what the true curve really produces
% from that same fuel, per kW of fuel) -- an aggregate so it can't be distorted
% by near-zero dispatch intervals, where a per-point ratio would blow up.
%   > 0 optimistic (planner overrates the FC -> over-dispatches -> reality
%       under-delivers -> planned-vs-actual gap pushed POSITIVE)
%   < 0 pessimistic (planner underrates it -> gap pushed NEGATIVE)
% This is what makes the two Gap(%) values below readable; see the explanation
% after the table.
bkConst = pwl_utils('fit', p5.PWL.eta_FC_e_func, p5.PWL.FC_H2_max, 1, 'FC_elec_const');
optimism = @(bx, by, v) (sum(pwl_utils('eval', bx, by, v)) ...
    - sum(p5.PWL.eta_FC_e_func(v/p5.PWL.FC_H2_max) .* v)) / sum(v);
opt5pwl   = optimism(p5.PWL.bkpt_e.x, p5.PWL.bkpt_e.y, C5pwl.PH2_5);
opt5const = optimism(bkConst.x,       bkConst.y,       C5const.PH2_5);

fprintf('\n%-24s %12s %12s %12s %12s %12s\n', 'Case 5 variant', 'Planned($)', 'Actual($)', 'Gap($)', 'Gap(%)', 'Optimism');
fprintf('%-24s %12.4f %12.4f %12.4f %12.2f %+12.4f\n', 'PWL (correct model)', C5pwl.plannedCost, C5pwl.actualCost, ...
    C5pwl.actualCost-C5pwl.plannedCost, 100*(C5pwl.actualCost-C5pwl.plannedCost)/abs(C5pwl.plannedCost), opt5pwl);
fprintf('%-24s %12.4f %12.4f %12.4f %12.2f %+12.4f\n', 'Constant efficiency', C5const.plannedCost, C5const.actualCost, ...
    C5const.actualCost-C5const.plannedCost, 100*(C5const.actualCost-C5const.plannedCost)/abs(C5const.plannedCost), opt5const);

relErrRealized = 100*(C5const.actualCost - C5pwl.actualCost)/abs(C5pwl.actualCost);
if relErrRealized >= 0
    moreOrLess = 'more';
else
    moreOrLess = 'less';
end
slopesTrue = diff(p5.PWL.bkpt_e.y) ./ diff(p5.PWL.bkpt_e.x);
slopeConst = diff(bkConst.y) / diff(bkConst.x);
fprintf(['\nDo NOT read the Gap(%%) column as a measure of model quality -- it is not one, and\n' ...
    'here it ranks the two models the wrong way round (the WRONG model shows the SMALLER\n' ...
    'gap, %.2f%% vs %.2f%%). Two separate things are mixed into that column: forecast error\n' ...
    '(actual solar/load differing from the day-ahead/intraday forecast) and modeling error\n' ...
    '(the planning model being wrong about its own fuel cell). Worse, the modeling part has\n' ...
    'a SIGN, shown in the Optimism column: it only widens the gap if the planning model is\n' ...
    'OPTIMISTIC about the fuel cell, and it NARROWS the gap if the model is pessimistic.\n' ...
    '\nThat is exactly what happens here. The constant-efficiency planning model is a single\n' ...
    'chord of slope %.4f, while the true curve''s marginal slopes over the segments the fuel\n' ...
    'cell actually operates in are %.4f / %.4f / %.4f -- all ABOVE that chord. So the\n' ...
    'constant-efficiency model systematically UNDER-states what its own fuel cell will\n' ...
    'deliver (Optimism %+.4f, i.e. pessimistic): it plans a higher cost ($%.4f vs $%.4f),\n' ...
    'reality then comes in better than it planned, and that credit partially cancels the\n' ...
    'forecast-driven overrun instead of adding to it -- shrinking its gap. The PWL row, whose\n' ...
    'planning model matches reality (Optimism %+.4f, essentially neutral), shows a gap that\n' ...
    'is very nearly pure forecast error. A pessimistic wrong model can therefore look BETTER\n' ...
    'on this statistic than a correct one, which is precisely why the gap cannot be used to\n' ...
    'rank models.\n' ...
    '\nComparing REALIZED cost (both evaluated against the one true curve, so this isolates\n' ...
    'the modeling choice from forecast noise): at THIS (gate) price constant efficiency\n' ...
    'costs %.2f%% %s than PWL -- the upper end of the range above, not the headline\n' ...
    '(literature comparison point: Huang et al. report 13.7%% for a constant-efficiency\n' ...
    'baseline against their true curve -- not the same system, curves, or price levels, so\n' ...
    'not a claim of matching their number, only the same kind of comparison).\n' ...
    'CO2: PWL=%.2f kg vs constant=%.2f kg (%+.2f kg). Reliability: PWL unmetE=%.3f kWh/%.3f\n' ...
    'violHrs vs constant unmetE=%.3f kWh/%.3f violHrs.\n'], ...
    100*(C5const.actualCost-C5const.plannedCost)/abs(C5const.plannedCost), ...
    100*(C5pwl.actualCost-C5pwl.plannedCost)/abs(C5pwl.plannedCost), ...
    slopeConst, slopesTrue(1), slopesTrue(2), slopesTrue(3), ...
    opt5const, C5const.plannedCost, C5pwl.plannedCost, opt5pwl, ...
    abs(relErrRealized), moreOrLess, C5pwl.emissions_kgCO2, C5const.emissions_kgCO2, ...
    C5const.emissions_kgCO2-C5pwl.emissions_kgCO2, V5pwl.unmetEnergy_kWh, V5pwl.violationHours, ...
    V5const.unmetEnergy_kWh, V5const.violationHours);

%% Network consequences: every case replayed through IEEE 33 -----------
% Post-hoc verification -- it cannot alter any dispatch, so every cost,
% CO2 and peak figure printed above is untouched by this section. Each
% case's own 5-minute grid exchange is substituted at the ONE hub's host
% bus and solved with the exact backward-forward sweep. This is the
% primary network evidence; the feeder-cap reliability columns above are
% retained for continuity with earlier sessions.
addpath('../month2_coupling_matrix_pwl_ieee33');
sysNet = ieee33_system_definition();

fprintf('\n=====================================================\n');
fprintf(' Network consequences on IEEE 33 (ONE hub at bus %d)\n', sysNet.hostBus);
fprintf('=====================================================\n');
fprintf('Unity power factor; voltages optimistic vs. a hub exchanging Q (network_verify.m).\n');
fprintf('Hub peak import %.2f%% of the %.0f kW feeder but %.0f%% of its host bus''s %.0f kW.\n\n', ...
    sysNet.penetrationFeeder_pct, sysNet.feederLoad_kW, ...
    sysNet.penetrationHostBus_pct, sysNet.hostBusLoad_kW);

netCases = {C1, C2, C3, C4, C5pwlDel, C5constDel};
netNames = {'1: Conventional', '2: Day-ahead only', '3: No robust reserve', ...
            '4: Full proposed', '5a: PWL (delivered)', '5b: Const-eff (deliv.)'};
NV = cell(1, numel(netCases));
for i = 1:numel(netCases)
    NV{i} = network_verify(sysNet, netCases{i}.Pg_imp5 - netCases{i}.Pg_exp5);
end

fprintf('%-24s %9s %7s %10s %13s %13s\n', 'Case', 'min V', 'worst', 'hrs<0.95', 'losses kWh', 'vs base');
fprintf('%-24s %9.4f %7d %10.2f %13.1f %13s\n', 'base: no hub at all', ...
    NV{1}.base_minV, NV{1}.base_minV_bus, 24.00, NV{1}.base_lossEnergy_kWh, '-');
for i = 1:numel(netCases)
    fprintf('%-24s %9.4f %7d %10.2f %13.1f %+13.1f\n', netNames{i}, ...
        NV{i}.minV, NV{i}.minV_bus, NV{i}.hoursBelowLimit, ...
        NV{i}.lossEnergy_kWh, NV{i}.dLossEnergy_kWh);
end

fprintf(['\nWHY THE DO-NOTHING BASELINE HAS THE BEST VOLTAGE (Case 1, %.4f pu). This looks\n' ...
    'wrong and is not. Case 1 serves its heat with a GAS BOILER, so the only electricity\n' ...
    'it draws at bus %d is its own electrical load -- no heat pump, no EV fleet charging,\n' ...
    'no battery pulling extra import during cheap hours. Every hub case electrifies heat\n' ...
    'and adds controllable load, so it draws MORE peak current down the long radial to\n' ...
    'the weakest bus on the feeder, and minimum voltage is set by peak current. Case 1\n' ...
    'wins on voltage by doing less, and pays for it in cost (%.0f%% higher) and CO2 (%.0f%%\n' ...
    'higher) -- it burns gas instead. That is the electrification trade-off stated\n' ...
    'plainly, not a defect in the hub cases.\n'], ...
    NV{1}.minV, sysNet.hostBus, ...
    100*(C1.actualCost-C4.actualCost)/C4.actualCost, ...
    100*(C1.emissions_kgCO2-C4.emissions_kgCO2)/C4.emissions_kgCO2);

fprintf(['\nThe hrs<0.95 column reads 24.00 for every row INCLUDING the no-hub base case:\n' ...
    '%d of 33 IEEE 33 buses already sit below 0.95 pu in the published benchmark, all day,\n' ...
    'with no hub present. It is a property of the feeder, not of any case here, and is\n' ...
    'shown only so it cannot later be mistaken for a hub-caused violation. The columns\n' ...
    'that carry information are min V and the loss delta.\n'], NV{1}.base_busesBelow);

% Is the cheapest dispatch also the best one for the network?
costs14 = [C1.actualCost, C2.actualCost, C3.actualCost, C4.actualCost];
minV14  = [NV{1}.minV, NV{2}.minV, NV{3}.minV, NV{4}.minV];
loss14  = [NV{1}.lossEnergy_kWh, NV{2}.lossEnergy_kWh, NV{3}.lossEnergy_kWh, NV{4}.lossEnergy_kWh];
[~, iCheap] = min(costs14);
[~, iBestV] = max(minV14);
[~, iBestL] = min(loss14);
fprintf(['\nIS THE CHEAPEST DISPATCH ALSO THE BEST ONE FOR THE NETWORK? Among Cases 1-4:\n' ...
    '  cheapest             : %s ($%.2f)\n' ...
    '  best minimum voltage : %s (%.4f pu)\n' ...
    '  lowest feeder losses : %s (%.1f kWh/day)\n'], ...
    netNames{iCheap}, costs14(iCheap), netNames{iBestV}, minV14(iBestV), ...
    netNames{iBestL}, loss14(iBestL));
if iCheap == iBestV && iCheap == iBestL
    fprintf('All three coincide, so on this profile cost and network quality do not conflict.\n');
else
    fprintf(['They do NOT all coincide. Cost-optimality and network-friendliness are different\n' ...
        'objectives, and separating them is precisely why the study is benchmarked on IEEE 33\n' ...
        'instead of on a scalar import cap.\n']);
end

if NV{4}.minV >= NV{1}.minV && NV{4}.lossEnergy_kWh <= NV{1}.lossEnergy_kWh
    verdict41 = 'also better for the network on both counts';
elseif NV{4}.minV < NV{1}.minV && NV{4}.lossEnergy_kWh > NV{1}.lossEnergy_kWh
    verdict41 = 'WORSE for the network on both counts';
else
    verdict41 = 'better on one network measure and worse on the other';
end
fprintf(['\nCase 4 against Case 1 concretely: $%.2f vs $%.2f (%.1f%% cheaper), minimum voltage\n' ...
    '%.4f vs %.4f pu (%+.4f), feeder losses %.1f vs %.1f kWh/day (%+.1f). The cheaper\n' ...
    'dispatch is %s.\n'], ...
    C4.actualCost, C1.actualCost, 100*(C1.actualCost-C4.actualCost)/C1.actualCost, ...
    NV{4}.minV, NV{1}.minV, NV{4}.minV-NV{1}.minV, ...
    NV{4}.lossEnergy_kWh, NV{1}.lossEnergy_kWh, NV{4}.lossEnergy_kWh-NV{1}.lossEnergy_kWh, ...
    verdict41);

fprintf(['\nDOES MODELLING ERROR PROPAGATE INTO GRID ERROR? Case 5a (PWL) vs 5b (constant\n' ...
    'efficiency), both at the delivered hydrogen price, both replayed through the same\n' ...
    'exact power flow:\n' ...
    '  minimum voltage  %.4f vs %.4f pu (%+.4f)\n' ...
    '  feeder losses    %.1f vs %.1f kWh/day (%+.1f)\n'], ...
    NV{5}.minV, NV{6}.minV, NV{6}.minV-NV{5}.minV, ...
    NV{5}.lossEnergy_kWh, NV{6}.lossEnergy_kWh, NV{6}.lossEnergy_kWh-NV{5}.lossEnergy_kWh);
if abs(NV{6}.minV - NV{5}.minV) < 5e-4 && abs(NV{6}.lossEnergy_kWh - NV{5}.lossEnergy_kWh) < 5
    fprintf(['Practically indistinguishable at the grid level. Getting the fuel cell''s\n' ...
        'part-load curve wrong costs money (0.20%%-1.47%%, above) but barely moves what the\n' ...
        'network sees, because the fuel cell is a modest part of a net injection dominated\n' ...
        'by load, PV and battery. Stated plainly: on this profile PWL fidelity is a COST\n' ...
        'accuracy question, not a grid accuracy one. A grid-only study could use coarse PWL.\n']);
else
    fprintf(['The two differ measurably at the grid level, so the modelling error does\n' ...
        'propagate: getting the part-load curve wrong changes what the network experiences,\n' ...
        'not only what the cost report says.\n']);
end

%% Plots
try
    figure('Position',[100 100 1000 700]);

    subplot(2,2,1);
    bar(cost); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('$/day'); title('Operational cost'); grid on;

    subplot(2,2,2);
    bar(emis); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('kgCO2/day'); title('Carbon emissions'); grid on;

    subplot(2,2,3);
    bar(peak); set(gca,'XTickLabel',{'1','2','3','4'});
    hold on; plot([0.5 4.5],[feederCap feederCap],'r--','LineWidth',1.2);
    ylabel('kW'); title('Peak grid import (dashed = feeder capacity for cases 2-4)'); grid on;

    subplot(2,2,4);
    bar([0 unmetE(2:4)]); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('kWh/day'); title('Unmet energy (feeder-capacity violations)'); grid on;

    sgtitle_text = 'Case studies: 1=Conventional, 2=Day-ahead only, 3=No robust reserve, 4=Full proposed system';
    annotation('textbox',[0.05 0.95 0.9 0.05],'String',sgtitle_text,'EdgeColor','none','HorizontalAlignment','center','FontWeight','bold');
catch plot_err
    fprintf('\n[plots skipped: %s]\n', plot_err.message);
end
