%MAIN_MONTH4A_CASE_STUDIES
%Thesis roadmap Month 4, item I: case studies quantifying cost, emissions,
%and reliability improvements from the energy hub / multi-timescale approach.
%
%   Four cases, each isolating one specific modeling contribution from
%   the rest of this project, so the improvement from each can be
%   attributed rather than only shown in aggregate:
%
%     Case 1 "Conventional"        : no PV/FC/heat pump/storage at all --
%                                     grid electricity + gas boiler heat.
%                                     The pre-energy-hub reference point.
%     Case 2 "Day-ahead only"      : the energy hub exists and is
%                                     scheduled by the day-ahead LP, but
%                                     executed OPEN LOOP -- no intraday/
%                                     real-time correction. Isolates the
%                                     value of the rolling multi-timescale
%                                     coordination layers.
%     Case 3 "No robust reserve"   : full closed-loop day-ahead+intraday+
%                                     real-time, but the day-ahead reserve
%                                     margin is disabled (reserveScale=0).
%                                     Isolates the value of the robustness
%                                     proxy.
%     Case 4 "Full proposed system": everything as built (robust day-ahead
%                                     + rolling intraday/real-time), the
%                                     complete approach this thesis proposes.
%     Case 5 "Constant efficiency"  : NOT part of the Case 1-4 progression
%                                     (it isolates PWL itself, not a
%                                     coordination/robustness layer) --
%                                     full Case-4-style closed loop, but
%                                     the PLANNING stack (day-ahead +
%                                     intraday) believes the fuel cell has
%                                     ONE constant efficiency instead of
%                                     the true nonlinear PWL curve
%                                     (opts.usePWL=false in
%                                     simulate_multiscale_day.m). The
%                                     physical realization always uses
%                                     the TRUE curve regardless -- the
%                                     fuel cell doesn't know what the
%                                     planner assumed about it -- so a
%                                     WRONG planning model can plan one
%                                     cost and realize a different one.
%                                     Run at BOTH DOE 2026 target prices
%                                     (H2_doeTargetDelivered $2.93/kg,
%                                     the like-for-like headline, and
%                                     H2_doeTargetGate $2.00/kg, an
%                                     optimistic bound -- see the three
%                                     named scenarios and the
%                                     production-vs-delivered
%                                     distinction in
%                                     multiscale_default_params.m), not
%                                     the H2_today default ($0.22/kWh =
%                                     $7.33/kg) that Cases 1-4 use. Those
%                                     are the scenarios in which the fuel
%                                     cell is economic at all: at today's
%                                     delivered cost it never dispatches
%                                     (confirmed across every
%                                     seed/uncertainty combination used
%                                     elsewhere in this project), so a
%                                     PWL-vs-constant comparison there
%                                     would be vacuous -- 0 fuel either
%                                     way, nothing measured. Asking what
%                                     the fuel cell's part-load model is
%                                     worth is only meaningful where the
%                                     fuel cell runs.
%                                     KEY RESULT: the PWL cost benefit is
%                                     UTILIZATION-DEPENDENT -- constant
%                                     efficiency costs several times more
%                                     at the optimistic gate price, where
%                                     ~2.5x as much fuel flows, than at the
%                                     like-for-like delivered price, so it
%                                     is reported as a range rather than a
%                                     single figure. Both percentages are
%                                     COMPUTED and printed at run time
%                                     rather than quoted here: a literal in
%                                     a comment goes stale the first time
%                                     anything upstream changes, which is
%                                     exactly what happened to the numbers
%                                     that used to sit on this line. The
%                                     cost-independent argument is
%                                     stronger: without the fill-order
%                                     binaries the LP produces a
%                                     physically impossible dispatch at
%                                     ANY price.
%                                     Cases 1-4 above are untouched and
%                                     keep the shared default p.
%
%   Reliability is checked against a SHARED feeder capacity limit
%   (p.reliability.feederCapMargin x Case 4's own day-ahead peak import
%   -- i.e. "the connection sized for the proposed system"), applied to
%   cases 2-4 so the comparison isolates coordination/robustness, not
%   different infrastructure sizing. Case 1 has no such cap (a
%   conventional system is simply sized for its own peak) but its much
%   higher peak import is reported as its own finding: the energy hub
%   materially reduces how large a grid connection is needed at all.
%
%   Depends on Month 3's dispatch stack (../month3_multiscale_optimization).
%
%   Run with:  main_month4a_case_studies

clear; clc;
addpath('../month3_multiscale_optimization');

p = multiscale_default_params();
fc = forecast_profiles(42);

fprintf('=====================================================\n');
fprintf(' Case studies: cost, emissions, reliability\n');
fprintf('=====================================================\n');

fprintf('\nRunning Case 1 (conventional: grid + gas boiler, no energy hub)...\n');
C1 = simulate_conventional_baseline(p, fc);

fprintf('Running Case 2 (energy hub, day-ahead only, open loop)...\n');
C2 = simulate_multiscale_day(p, fc, struct('useIntraday', false, 'reserveScale', 1.0));

fprintf('Running Case 3 (energy hub, full rolling dispatch, no robust reserve)...\n');
C3 = simulate_multiscale_day(p, fc, struct('useIntraday', true, 'reserveScale', 0.0));

fprintf('Running Case 4 (energy hub, full proposed system)...\n');
C4 = simulate_multiscale_day(p, fc, struct('useIntraday', true, 'reserveScale', 1.0));

% Reliability threshold. feeder_capacity.m is consumed ONLY by
% reliability_check below, AFTER every case has been simulated -- it never
% enters simulate_multiscale_day or any dispatch constraint, so the choice
% of basis cannot move any case's cost, CO2 or peak. It can only move
% unmetE and violHrs. Both bases are computed so the reader can see whether
% the Case 4 advantage survives a threshold Case 4 did not define.
[feederCap, capLabel]         = feeder_capacity(p, fc, 'design');
[feederCapC4, capLabelC4]     = feeder_capacity(p, fc, 'case4', C4.dayaheadPeakImport);
fprintf('\nFeeder capacity, DEFAULT basis : %.2f kW  [%s]\n', feederCap, capLabel);
fprintf('Feeder capacity, comparison basis: %.2f kW  [%s]\n', feederCapC4, capLabelC4);

V2 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, feederCap);
V3 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, feederCap);
V4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, feederCap);

V2c4 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, feederCapC4);
V3c4 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, feederCapC4);
V4c4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, feederCapC4);

% EFFICIENCY, the fourth assessment criterion in the thesis brief. Computed
% from the completed dispatches -- nothing is re-solved. hub_efficiency.m
% documents the boundary; the two ratios answer different questions and are
% both reported because neither alone is honest:
%   etaHub       = delivered / PURCHASED energy. Can exceed 100% because the
%                  heat pump lifts ambient heat nobody paid for.
%   etaHubThermo = delivered / (purchased + ambient lifted). First-law
%                  bounded, and the one on which the CONVENTIONAL case wins.
E1 = hub_efficiency(p, fc, C1); E2 = hub_efficiency(p, fc, C2);
E3 = hub_efficiency(p, fc, C3); E4 = hub_efficiency(p, fc, C4);
etaHubPct    = 100*[E1.etaHub, E2.etaHub, E3.etaHub, E4.etaHub];
etaThermoPct = 100*[E1.etaHubThermo, E2.etaHubThermo, E3.etaHubThermo, E4.etaHubThermo];
effResid     = [E1.balanceResidual_kWh, E2.balanceResidual_kWh, ...
                E3.balanceResidual_kWh, E4.balanceResidual_kWh];

cases = {'1: Conventional', '2: Day-ahead only', '3: No robust reserve', '4: Full proposed'};
cost = [C1.actualCost, C2.actualCost, C3.actualCost, C4.actualCost];
emis = [C1.emissions_kgCO2, C2.emissions_kgCO2, C3.emissions_kgCO2, C4.emissions_kgCO2];
peak = [C1.dayaheadPeakImport, max(C2.Pg_imp5), max(C3.Pg_imp5), max(C4.Pg_imp5)];
unmetE = [NaN, V2.unmetEnergy_kWh, V3.unmetEnergy_kWh, V4.unmetEnergy_kWh];
violHrs = [NaN, V2.violationHours, V3.violationHours, V4.violationHours];

fprintf('\n%-24s %10s %12s %10s %14s %12s %11s %11s\n', 'Case', 'Cost($)', 'CO2(kg)', 'Peak(kW)', 'UnmetE(kWh)', 'ViolHrs', 'etaHub(%)', 'etaTherm(%)');
for i = 1:4
    if isnan(unmetE(i))
        fprintf('%-24s %10.2f %12.1f %10.1f %14s %12s %11.1f %11.1f\n', cases{i}, cost(i), emis(i), peak(i), 'n/a', 'n/a', etaHubPct(i), etaThermoPct(i));
    else
        fprintf('%-24s %10.2f %12.1f %10.1f %14.2f %12.2f %11.1f %11.1f\n', cases{i}, cost(i), emis(i), peak(i), unmetE(i), violHrs(i), etaHubPct(i), etaThermoPct(i));
    end
end
fprintf('Energy-balance residual per case (kWh/day): %+.3f %+.3f %+.3f %+.3f\n', effResid);
fprintf(['\nTHE TWO EFFICIENCY COLUMNS DISAGREE ABOUT WHO WINS, AND BOTH ARE RIGHT.\n' ...
    'On PURCHASED energy the hub is far ahead (%.1f%% against the conventional\n' ...
    'case''s %.1f%%) because its heat pump delivers heat it never bought -- lifted\n' ...
    'from ambient air at a COP of %.1f. On FIRST-LAW energy, which charges the hub\n' ...
    'for that ambient heat, the CONVENTIONAL CASE IS MORE EFFICIENT: %.1f%% against\n' ...
    '%.1f%%. That is not a defect in the hub and it is not softened here.\n' ...
    '\nTHE MECHANISM IS CONVERSION COUNT. The conventional case has two paths and\n' ...
    'both are short: grid electricity straight to load, and gas through one boiler\n' ...
    'at %.0f%%. The hub interposes a PV inverter, a fuel cell, four storage devices\n' ...
    'with round-trip losses, and -- the largest single term -- storage SELF-DISCHARGE\n' ...
    'of %.0f kWh/day, most of it the building thermal mass leaking at %.0f%%/hour.\n' ...
    'Every extra conversion costs first-law efficiency. The hub buys cost and carbon\n' ...
    'reductions with thermodynamic efficiency, and the trade is only visible if both\n' ...
    'numbers are printed.\n'], ...
    etaHubPct(4), etaHubPct(1), p.HeatPump.COP, etaThermoPct(1), etaThermoPct(4), ...
    100*p.Boiler.eta, E4.lossSelfDischarge_kWh, 100*p.Building.selfLoss);

%% Reliability under both threshold bases -----------------------------
fprintf('\n--- Reliability under BOTH capacity bases (cost/CO2/peak unaffected) ---\n');
fprintf('The reliability threshold is the one metric whose basis is a methodological\n');
fprintf('choice, so both are shown. Cost, CO2 and peak above cannot move with it:\n');
fprintf('feeder_capacity.m feeds only reliability_check.m, after all cases are solved.\n\n');
fprintf('%-24s %11s %10s   %11s %10s\n', '', 'design', '', 'case4-derived', '');
fprintf('%-24s %11s %10s   %11s %10s\n', 'Case', 'UnmetE', 'ViolHrs', 'UnmetE', 'ViolHrs');
relNames = {'2: Day-ahead only', '3: No robust reserve', '4: Full proposed'};
Vd = {V2, V3, V4}; Vc = {V2c4, V3c4, V4c4};
for i = 1:3
    fprintf('%-24s %11.2f %10.2f   %11.2f %10.2f\n', relNames{i}, ...
        Vd{i}.unmetEnergy_kWh, Vd{i}.violationHours, ...
        Vc{i}.unmetEnergy_kWh, Vc{i}.violationHours);
end

%% Threshold sensitivity ----------------------------------------------
% The three cases' realized peaks differ by under 2 kW, so the binary
% "violations vs. no violations" verdict is inherently threshold-sensitive.
% Sweep it rather than assert a single number.
fprintf('\n--- Threshold sensitivity (violation hours; realized peaks C2/C3/C4 = %.2f/%.2f/%.2f kW) ---\n', ...
    max(C2.Pg_imp5), max(C3.Pg_imp5), max(C4.Pg_imp5));
% The bracketing caps are expressed as FRACTIONS of the design capacity, not
% as absolute kW. Hardcoded kW values silently stop bracketing the peaks the
% moment the hub is resized -- at the current size a fixed [90 95 100 106 110]
% list sat entirely below every case's peak and reported nothing but
% saturation. These fractions put three points below and one above the two
% capacities under test at any hub size.
capSweep = [feederCap*[0.85 0.90 0.95 0.98] feederCap feederCapC4 feederCap*1.02];
capSweep = sort(unique(round(capSweep*100)/100));
fprintf('%10s %10s %10s %10s   %s\n', 'cap(kW)', 'C2', 'C3', 'C4', 'unmetE C2/C3/C4 (kWh)');
for cc = capSweep
    v2 = reliability_check(C2.Pg_imp5, C2.Pg_exp5, cc);
    v3 = reliability_check(C3.Pg_imp5, C3.Pg_exp5, cc);
    v4 = reliability_check(C4.Pg_imp5, C4.Pg_exp5, cc);
    fprintf('%10.2f %10.2f %10.2f %10.2f   %.2f / %.2f / %.2f\n', cc, ...
        v2.violationHours, v3.violationHours, v4.violationHours, ...
        v2.unmetEnergy_kWh, v3.unmetEnergy_kWh, v4.unmetEnergy_kWh);
end

if V4.violationHours < min(V2.violationHours, V3.violationHours)
    survives = 'YES';
else
    survives = 'NO';
end
% Exact window in which Case 4 is the ONLY case inside the limit:
% caps >= Case 4's own peak but below the next-lowest peak.
pk4      = max(C4.Pg_imp5);
pkOthers = min(max(C2.Pg_imp5), max(C3.Pg_imp5));
pkAll    = max(max(C2.Pg_imp5), max(C3.Pg_imp5));
pkSpread = pkAll - pk4;
fprintf(['\nDoes Case 4''s reliability advantage survive an independently-set threshold? %s.\n' ...
    'Under the design-basis cap (%.2f kW, built only from load and nameplate ratings --\n' ...
    'no dispatch strategy involved) Case 4 still records %.2f violation hours against\n' ...
    '%.2f and %.2f for Cases 2 and 3.\n' ...
    '\nBut the sweep above shows how NARROW that verdict is, and this qualification\n' ...
    'belongs with the result: the three cases'' realized peaks lie within %.2f kW of each\n' ...
    'other, so Case 4 is the ONLY case inside the limit just for caps in [%.2f, %.2f) kW\n' ...
    '-- a window %.2f kW wide, about %.1f%% of the peak itself. Set the cap below %.2f kW\n' ...
    'and Case 4 violates too; set it at or above %.2f kW and NONE of them violate. The\n' ...
    'binary "zero violations" headline is therefore an artifact of where the line is\n' ...
    'drawn, and should not be quoted on its own.\n' ...
    '\nIn fairness the design cap (%.2f kW) does land inside that narrow window, and it\n' ...
    'is only fair to flag that rather than let it pass: the diversity factor (%.2f) was\n' ...
    'chosen from the load composition -- few large controllable loads, so high\n' ...
    'coincidence -- and NOT reverse-engineered from the answer, but a lower factor would\n' ...
    'change the verdict. At 0.75-0.80 the cap falls to roughly %.0f-%.0f kW and, as the\n' ...
    'sweep shows, ALL THREE cases then violate. The reader should treat "Case 4 alone is\n' ...
    'clean" as conditional on a connection contracted tightly around the system''s own\n' ...
    'peak.\n' ...
    '\nWhat IS robust is the ORDERING of unmet energy: at every cap in the sweep where\n' ...
    'anything violates at all, Case 4 has the lowest unmet energy and Case 3 (no robust\n' ...
    'reserve) the highest -- including at the caps low enough that all three breach the\n' ...
    'limit and the binary violation count no longer separates them at all. That ranking\n' ...
    'holds across the whole range rather than at one threshold, so it -- not the zero --\n' ...
    'is the defensible reliability claim.\n'], ...
    survives, feederCap, V4.violationHours, V2.violationHours, V3.violationHours, ...
    pkSpread, pk4, pkOthers, pkOthers - pk4, 100*(pkOthers - pk4)/pk4, pk4, pkAll, ...
    feederCap, p.reliability.diversityFactor, ...
    feederCap*0.75/p.reliability.diversityFactor, ...
    feederCap*0.80/p.reliability.diversityFactor);

fprintf('\n--- Improvements relative to Case 1 (conventional) ---\n');
fprintf('Case 4 cost reduction: %.1f%%\n', 100*(cost(1)-cost(4))/cost(1));
fprintf('Case 4 CO2 reduction:  %.1f%%\n', 100*(emis(1)-emis(4))/emis(1));
fprintf(['\nWHAT THESE TWO NUMBERS DO AND DO NOT MEASURE -- read before quoting them.\n' ...
    'They compare a system WITH PV, battery, EV and heat pump against one with NONE of\n' ...
    'them: Case 1 is grid import plus a gas boiler and has no PV at all, while Case 4\n' ...
    'has %.0f kWh/day of free solar. Most of the %.1f%% is therefore the value of OWNING\n' ...
    'THE EQUIPMENT, not the value of the energy-hub modelling this thesis contributes.\n' ...
    'Any competently dispatched system with the same hardware would capture most of it.\n' ...
    'Quoting %.1f%% as a result of the modelling work would be a category error, and it\n' ...
    'should never be cited without saying what it compares.\n' ...
    '\nThe numbers that DO isolate this thesis''s own contributions are the ablations\n' ...
    'below and Case 5, and they are appropriately smaller:\n' ...
    '  rolling intraday/real-time layers  Case 2 vs 4\n' ...
    '  robust reserve margin              Case 3 vs 4\n' ...
    '  PWL vs constant efficiency         Case 5 (a RANGE, not a number -- the benefit is\n' ...
    '                                     utilization-dependent and is computed and\n' ...
    '                                     printed at both hydrogen prices below)\n' ...
    'Those are the defensible claims for the modelling. The %.1f%% belongs in a sentence\n' ...
    'about electrification and on-site generation, not about optimization.\n'], ...
    sum(C4.DA.Ps), 100*(cost(1)-cost(4))/cost(1), 100*(cost(1)-cost(4))/cost(1), ...
    100*(cost(1)-cost(4))/cost(1));
fprintf(['Peak grid import: Case 1 = %.1f kW vs. Case 4 = %.1f kW -- NOT a reduction.\n' ...
    'Case 4 serves strictly more than Case 1 (EV fleet charging, heat-pump electrification\n' ...
    'of what was gas heat in Case 1), and its day-ahead LP deliberately imports MORE than\n' ...
    'instantaneous need during cheap overnight hours to pre-charge storage for later --\n' ...
    'a real, honest finding: cost/emission optimality and peak-shaving are different\n' ...
    'objectives, and this system was optimized for the former. A peak-shaving objective\n' ...
    '(or a demand charge in the price signal) would need to be added explicitly to also\n' ...
    'control for the latter -- it does not fall out of energy-cost minimization alone.\n'], peak(1), peak(4));

fprintf('\n--- Value of each contribution (relative to the FULL Case 4) ---\n');
fprintf('Removing intraday/real-time correction (Case 2 vs 4): cost %+.1f%%, unmet energy %+.2f kWh, violations %+.2f h\n', ...
    100*(cost(2)-cost(4))/cost(4), unmetE(2)-unmetE(4), violHrs(2)-violHrs(4));
fprintf('Removing the robust reserve margin (Case 3 vs 4):     cost %+.1f%%, unmet energy %+.2f kWh, violations %+.2f h\n', ...
    100*(cost(3)-cost(4))/cost(4), unmetE(3)-unmetE(4), violHrs(3)-violHrs(4));

%% Case 5: PWL vs. constant fuel cell efficiency (isolates PWL itself) ------
fprintf('\n=====================================================\n');
fprintf(' Case 5: PWL vs. constant fuel cell efficiency\n');
fprintf('=====================================================\n');
fprintf(['Run at BOTH DOE 2026 target prices, not the H2_today default ($%.2f/kWh =\n' ...
    '$%.2f/kg) used by Cases 1-4. At today''s delivered cost the fuel cell never\n' ...
    'dispatches, so a PWL-vs-constant comparison there would weigh 0 fuel against 0\n' ...
    'fuel and measure nothing -- what a part-load model is worth is only a meaningful\n' ...
    'question where the component actually runs. The two target prices differ in COST\n' ...
    'BASIS (see multiscale_default_params.m):\n' ...
    '  H2_doeTargetDelivered  $%.4f/kWh = $%.2f/kg -- DOE''s 2026 PRODUCTION target\n' ...
    '        carried to the meter with this project''s own delivery markup (%.3fx).\n' ...
    '        LIKE-FOR-LIKE against H2_today; read this as the headline.\n' ...
    '  H2_doeTargetGate       $%.4f/kWh = $%.2f/kg -- the same target at the\n' ...
    '        production gate, unmodified. OPTIMISTIC BOUND (delivery assumed free).\n' ...
    'Cases 1-4 above are untouched.\n'], ...
    p.scenarios.H2_today, p.scenarios.H2_today*p.scenarios.H2_kWhPerKg, ...
    p.scenarios.H2_doeTargetDelivered, p.scenarios.H2_doeTargetDelivered*p.scenarios.H2_kWhPerKg, ...
    p.scenarios.H2_deliveryMarkup, ...
    p.scenarios.H2_doeTargetGate, p.scenarios.H2_doeTargetGate*p.scenarios.H2_kWhPerKg);

% p5 stays on the GATE price: the detailed Optimism diagnostic and its
% explanation further below are anchored to that run.
p5 = p;
p5.price_H2 = p.scenarios.H2_doeTargetGate;
p5del = p;
p5del.price_H2 = p.scenarios.H2_doeTargetDelivered;

fprintf('\nRunning Case 5 at the DELIVERED target (like-for-like)...\n');
C5pwlDel   = simulate_multiscale_day(p5del, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', true));
C5constDel = simulate_multiscale_day(p5del, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', false));

fprintf('Running Case 5 at the GATE target (optimistic bound)...\n');
C5pwl   = simulate_multiscale_day(p5, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', true));
C5const = simulate_multiscale_day(p5, fc, struct('useIntraday', true, 'reserveScale', 1.0, 'usePWL', false));

V5pwl   = reliability_check(C5pwl.Pg_imp5,   C5pwl.Pg_exp5,   feederCap);
V5const = reliability_check(C5const.Pg_imp5, C5const.Pg_exp5, feederCap);

%% Headline: the PWL benefit scales with fuel-cell utilization ---------
relDel  = 100*(C5constDel.actualCost - C5pwlDel.actualCost)/abs(C5pwlDel.actualCost);
relGate = 100*(C5const.actualCost    - C5pwl.actualCost)   /abs(C5pwl.actualCost);
fuelDel  = sum(C5pwlDel.DA.PH2);   hrsDel  = sum(C5pwlDel.DA.PH2 > 1e-6);
fuelGate = sum(C5pwl.DA.PH2);      hrsGate = sum(C5pwl.DA.PH2 > 1e-6);

fprintf('\n%-26s %14s %14s %14s %12s\n', 'Hydrogen price', 'FC fuel(kWh)', 'PWL($)', 'const($)', 'const vs PWL');
fprintf('%-26s %14.1f %14.4f %14.4f %11.2f%%\n', ...
    sprintf('$%.2f/kg delivered', p5del.price_H2*p.scenarios.H2_kWhPerKg), ...
    fuelDel, C5pwlDel.actualCost, C5constDel.actualCost, relDel);
fprintf('%-26s %14.1f %14.4f %14.4f %11.2f%%\n', ...
    sprintf('$%.2f/kg gate', p5.price_H2*p.scenarios.H2_kWhPerKg), ...
    fuelGate, C5pwl.actualCost, C5const.actualCost, relGate);

fprintf(['\nTHE PWL COST BENEFIT IS UTILIZATION-DEPENDENT, and this must be read as a range,\n' ...
    'not a single number. Modelling the fuel cell with a constant efficiency instead of\n' ...
    'PWL costs %.2f%% more at the like-for-like DELIVERED price (%.0f kWh of fuel over %d\n' ...
    'hours) but %.2f%% more at the optimistic GATE price (%.0f kWh over %d hours). The\n' ...
    'mechanism is not subtle: a part-load model can only matter in proportion to how much\n' ...
    'energy actually flows through the nonlinear device, and %.1fx more fuel flows at the\n' ...
    'gate price. Quoting %.2f%% alone would be quietly conditioned on the more optimistic\n' ...
    'of the two cost bases, so both are reported. On the like-for-like basis the cost\n' ...
    'benefit is real but modest -- %.2f%% is a smaller claim than %.2f%%, and stating that\n' ...
    'plainly is the point.\n' ...
    '\nTHE VALIDITY ARGUMENT DOES NOT DEPEND ON COST AT ALL, and is the stronger one. The\n' ...
    'PWL segments and fill-order binaries exist to keep the dispatch PHYSICALLY POSSIBLE,\n' ...
    'not to save money. Without the ordering binaries the LP relaxation fills segment 2\n' ...
    'while segment 1 is still only fractionally full (verified counterfactual: PH2seg(2)\n' ...
    '> 0 while segment 1 is only 15%% full, %.1f of %.1f kW), which reports more electricity\n' ...
    'per unit hydrogen than the device can physically produce. That defect exists at EVERY\n' ...
    'price, including ones where the cost difference rounds to zero. A model that violates\n' ...
    'the machine it describes is wrong irrespective of what the error costs on a given\n' ...
    'day, so the case for the PWL/MILP formulation rests on correctness first and\n' ...
    'economics second.\n'], ...
    relDel, fuelDel, hrsDel, relGate, fuelGate, hrsGate, ...
    fuelGate/fuelDel, relGate, relDel, relGate, ...
    0.1525*p.PWL.bkpt_e.x(2), p.PWL.bkpt_e.x(2));

fprintf(['\nThe detailed diagnostic below is for the GATE run (the higher-throughput case,\n' ...
    'where the modeling effect is clearest).\n']);

% OPTIMISM DIAGNOSTIC: does the planning model over- or under-state what the
% fuel cell actually delivers, over the fuel levels it actually dispatched?
% Fuel-weighted over the whole day (total electricity the planner believed its
% own committed fuel would produce, minus what the true curve really produces
% from that same fuel, per kW of fuel) -- an aggregate so it can't be distorted
% by near-zero dispatch intervals, where a per-point ratio would blow up.
%   > 0 optimistic (planner overrates the FC -> over-dispatches -> reality
%       under-delivers -> planned-vs-actual gap pushed POSITIVE)
%   < 0 pessimistic (planner underrates it -> gap pushed NEGATIVE)
% This is what makes the two Gap(%) values below readable; see the explanation
% after the table.
bkConst = pwl_utils('fit', p5.PWL.eta_FC_e_func, p5.PWL.FC_H2_max, 1, 'FC_elec_const');
% fc_true_output rather than an inline eta_FC_e_func(v/Pmax).*v: the solver
% returns tiny NEGATIVE fuel values for idle hours, sqrt() of which is
% complex and silently contaminates everything downstream. See its header.
optimism = @(bx, by, v) (sum(pwl_utils('eval', bx, by, max(v(:),0))) ...
    - sum(fc_true_output(p5, v))) / sum(max(v(:),0));
opt5pwl   = optimism(p5.PWL.bkpt_e.x, p5.PWL.bkpt_e.y, C5pwl.PH2_5);
opt5const = optimism(bkConst.x,       bkConst.y,       C5const.PH2_5);

fprintf('\n%-24s %12s %12s %12s %12s %12s\n', 'Case 5 variant', 'Planned($)', 'Actual($)', 'Gap($)', 'Gap(%)', 'Optimism');
fprintf('%-24s %12.4f %12.4f %12.4f %12.2f %+12.4f\n', 'PWL (correct model)', C5pwl.plannedCost, C5pwl.actualCost, ...
    C5pwl.actualCost-C5pwl.plannedCost, 100*(C5pwl.actualCost-C5pwl.plannedCost)/abs(C5pwl.plannedCost), opt5pwl);
fprintf('%-24s %12.4f %12.4f %12.4f %12.2f %+12.4f\n', 'Constant efficiency', C5const.plannedCost, C5const.actualCost, ...
    C5const.actualCost-C5const.plannedCost, 100*(C5const.actualCost-C5const.plannedCost)/abs(C5const.plannedCost), opt5const);

relErrRealized = 100*(C5const.actualCost - C5pwl.actualCost)/abs(C5pwl.actualCost);
if relErrRealized >= 0
    moreOrLess = 'more';
else
    moreOrLess = 'less';
end
slopesTrue = diff(p5.PWL.bkpt_e.y) ./ diff(p5.PWL.bkpt_e.x);
slopeConst = diff(bkConst.y) / diff(bkConst.x);
fprintf(['\nDo NOT read the Gap(%%) column as a measure of model quality -- it is not one, and\n' ...
    'here it ranks the two models the wrong way round (the WRONG model shows the SMALLER\n' ...
    'gap, %.2f%% vs %.2f%%). Two separate things are mixed into that column: forecast error\n' ...
    '(actual solar/load differing from the day-ahead/intraday forecast) and modeling error\n' ...
    '(the planning model being wrong about its own fuel cell). Worse, the modeling part has\n' ...
    'a SIGN, shown in the Optimism column: it only widens the gap if the planning model is\n' ...
    'OPTIMISTIC about the fuel cell, and it NARROWS the gap if the model is pessimistic.\n' ...
    '\nThat is exactly what happens here. The constant-efficiency planning model is a single\n' ...
    'chord of slope %.4f, while the true curve''s marginal slopes over the segments the fuel\n' ...
    'cell actually operates in are %.4f / %.4f / %.4f -- all ABOVE that chord. So the\n' ...
    'constant-efficiency model systematically UNDER-states what its own fuel cell will\n' ...
    'deliver (Optimism %+.4f, i.e. pessimistic): it plans a higher cost ($%.4f vs $%.4f),\n' ...
    'reality then comes in better than it planned, and that credit partially cancels the\n' ...
    'forecast-driven overrun instead of adding to it -- shrinking its gap. The PWL row, whose\n' ...
    'planning model matches reality (Optimism %+.4f, essentially neutral), shows a gap that\n' ...
    'is very nearly pure forecast error. A pessimistic wrong model can therefore look BETTER\n' ...
    'on this statistic than a correct one, which is precisely why the gap cannot be used to\n' ...
    'rank models.\n' ...
    '\nComparing REALIZED cost (both evaluated against the one true curve, so this isolates\n' ...
    'the modeling choice from forecast noise): at THIS (gate) price constant efficiency\n' ...
    'costs %.2f%% %s than PWL -- the upper end of the range above, not the headline\n' ...
    '(literature comparison point: Huang et al. report 13.7%% for a constant-efficiency\n' ...
    'baseline against their true curve -- not the same system, curves, or price levels, so\n' ...
    'not a claim of matching their number, only the same kind of comparison).\n' ...
    'CO2: PWL=%.2f kg vs constant=%.2f kg (%+.2f kg). Reliability: PWL unmetE=%.3f kWh/%.3f\n' ...
    'violHrs vs constant unmetE=%.3f kWh/%.3f violHrs.\n'], ...
    100*(C5const.actualCost-C5const.plannedCost)/abs(C5const.plannedCost), ...
    100*(C5pwl.actualCost-C5pwl.plannedCost)/abs(C5pwl.plannedCost), ...
    slopeConst, slopesTrue(1), slopesTrue(2), slopesTrue(3), ...
    opt5const, C5const.plannedCost, C5pwl.plannedCost, opt5pwl, ...
    abs(relErrRealized), moreOrLess, C5pwl.emissions_kgCO2, C5const.emissions_kgCO2, ...
    C5const.emissions_kgCO2-C5pwl.emissions_kgCO2, V5pwl.unmetEnergy_kWh, V5pwl.violationHours, ...
    V5const.unmetEnergy_kWh, V5const.violationHours);

%% Network consequences: every case replayed through IEEE 33 -----------
% Post-hoc verification -- it cannot alter any dispatch, so every cost,
% CO2 and peak figure printed above is untouched by this section. Each
% case's own 5-minute grid exchange is substituted at the ONE hub's host
% bus and solved with the exact backward-forward sweep. This is the
% primary network evidence; the feeder-cap reliability columns above are
% retained for continuity with earlier sessions.
addpath('../month2_coupling_matrix_pwl_ieee33');
sysNet = ieee33_system_definition();

fprintf('\n=====================================================\n');
fprintf(' Network consequences on IEEE 33 (ONE hub at bus %d)\n', sysNet.hostBus);
fprintf('=====================================================\n');
fprintf('Unity power factor; voltages optimistic vs. a hub exchanging Q (network_verify.m).\n');
fprintf('Hub peak import %.2f%% of the %.0f kW feeder but %.0f%% of its host bus''s %.0f kW.\n\n', ...
    sysNet.penetrationFeeder_pct, sysNet.feederLoad_kW, ...
    sysNet.penetrationHostBus_pct, sysNet.hostBusLoad_kW);

netCases = {C1, C2, C3, C4, C5pwlDel, C5constDel};
netNames = {'1: Conventional', '2: Day-ahead only', '3: No robust reserve', ...
            '4: Full proposed', '5a: PWL (delivered)', '5b: Const-eff (deliv.)'};
NV = cell(1, numel(netCases));
for i = 1:numel(netCases)
    NV{i} = network_verify(sysNet, netCases{i}.Pg_imp5 - netCases{i}.Pg_exp5);
end

fprintf('%-24s %9s %7s %10s %13s %13s\n', 'Case', 'min V', 'worst', 'hrs<0.95', 'losses kWh', 'vs base');
fprintf('%-24s %9.4f %7d %10.2f %13.1f %13s\n', 'base: no hub at all', ...
    NV{1}.base_minV, NV{1}.base_minV_bus, 24.00, NV{1}.base_lossEnergy_kWh, '-');
for i = 1:numel(netCases)
    fprintf('%-24s %9.4f %7d %10.2f %13.1f %+13.1f\n', netNames{i}, ...
        NV{i}.minV, NV{i}.minV_bus, NV{i}.hoursBelowLimit, ...
        NV{i}.lossEnergy_kWh, NV{i}.dLossEnergy_kWh);
end

fprintf(['\nWHY THE DO-NOTHING BASELINE HAS THE BEST VOLTAGE (Case 1, %.4f pu). This looks\n' ...
    'wrong and is not. Case 1 serves its heat with a GAS BOILER, so the only electricity\n' ...
    'it draws at bus %d is its own electrical load -- no heat pump, no EV fleet charging,\n' ...
    'no battery pulling extra import during cheap hours. Every hub case electrifies heat\n' ...
    'and adds controllable load, so it draws MORE peak current through the trunk branches\n' ...
    'that feed the whole feeder, including the long radial down to bus %d, and minimum\n' ...
    'voltage is set by peak current. Case 1 wins on voltage by doing less, and pays for it\n' ...
    'in cost (%.0f%% higher) and CO2 (%.0f%% higher) -- it burns gas instead. That is the\n' ...
    'electrification trade-off stated plainly, not a defect in the hub cases.\n'], ...
    NV{1}.minV, sysNet.hostBus, NV{1}.base_minV_bus, ...
    100*(C1.actualCost-C4.actualCost)/C4.actualCost, ...
    100*(C1.emissions_kgCO2-C4.emissions_kgCO2)/C4.emissions_kgCO2);

fprintf(['\nThe hrs<0.95 column reads 24.00 for every row INCLUDING the no-hub base case:\n' ...
    '%d of 33 IEEE 33 buses already sit below 0.95 pu in the published benchmark, all day,\n' ...
    'with no hub present. It is a property of the feeder, not of any case here, and is\n' ...
    'shown only so it cannot later be mistaken for a hub-caused violation. The columns\n' ...
    'that carry information are min V and the loss delta.\n'], NV{1}.base_busesBelow);

% Is the cheapest dispatch also the best one for the network?
costs14 = [C1.actualCost, C2.actualCost, C3.actualCost, C4.actualCost];
minV14  = [NV{1}.minV, NV{2}.minV, NV{3}.minV, NV{4}.minV];
loss14  = [NV{1}.lossEnergy_kWh, NV{2}.lossEnergy_kWh, NV{3}.lossEnergy_kWh, NV{4}.lossEnergy_kWh];
[~, iCheap] = min(costs14);
[~, iBestV] = max(minV14);
[~, iBestL] = min(loss14);
fprintf(['\nIS THE CHEAPEST DISPATCH ALSO THE BEST ONE FOR THE NETWORK? Among Cases 1-4:\n' ...
    '  cheapest             : %s ($%.2f)\n' ...
    '  best minimum voltage : %s (%.4f pu)\n' ...
    '  lowest feeder losses : %s (%.1f kWh/day)\n'], ...
    netNames{iCheap}, costs14(iCheap), netNames{iBestV}, minV14(iBestV), ...
    netNames{iBestL}, loss14(iBestL));
if iCheap == iBestV && iCheap == iBestL
    fprintf('All three coincide, so on this profile cost and network quality do not conflict.\n');
else
    fprintf(['They do NOT all coincide. Cost-optimality and network-friendliness are different\n' ...
        'objectives, and separating them is precisely why the study is benchmarked on IEEE 33\n' ...
        'instead of on a scalar import cap.\n']);
end

if NV{4}.minV >= NV{1}.minV && NV{4}.lossEnergy_kWh <= NV{1}.lossEnergy_kWh
    verdict41 = 'also better for the network on both counts';
elseif NV{4}.minV < NV{1}.minV && NV{4}.lossEnergy_kWh > NV{1}.lossEnergy_kWh
    verdict41 = 'WORSE for the network on both counts';
else
    verdict41 = 'better on one network measure and worse on the other';
end
fprintf(['\nCase 4 against Case 1 concretely: $%.2f vs $%.2f (%.1f%% cheaper), minimum voltage\n' ...
    '%.4f vs %.4f pu (%+.4f), feeder losses %.1f vs %.1f kWh/day (%+.1f). The cheaper\n' ...
    'dispatch is %s.\n'], ...
    C4.actualCost, C1.actualCost, 100*(C1.actualCost-C4.actualCost)/C1.actualCost, ...
    NV{4}.minV, NV{1}.minV, NV{4}.minV-NV{1}.minV, ...
    NV{4}.lossEnergy_kWh, NV{1}.lossEnergy_kWh, NV{4}.lossEnergy_kWh-NV{1}.lossEnergy_kWh, ...
    verdict41);

fprintf(['\nDOES MODELLING ERROR PROPAGATE INTO GRID ERROR? Case 5a (PWL) vs 5b (constant\n' ...
    'efficiency), both at the delivered hydrogen price, both replayed through the same\n' ...
    'exact power flow:\n' ...
    '  minimum voltage  %.4f vs %.4f pu (%+.4f)\n' ...
    '  feeder losses    %.1f vs %.1f kWh/day (%+.1f)\n'], ...
    NV{5}.minV, NV{6}.minV, NV{6}.minV-NV{5}.minV, ...
    NV{5}.lossEnergy_kWh, NV{6}.lossEnergy_kWh, NV{6}.lossEnergy_kWh-NV{5}.lossEnergy_kWh);
if abs(NV{6}.minV - NV{5}.minV) < 5e-4 && abs(NV{6}.lossEnergy_kWh - NV{5}.lossEnergy_kWh) < 5
    fprintf(['Practically indistinguishable at the grid level. Getting the fuel cell''s\n' ...
        'part-load curve wrong costs money (%.2f%%-%.2f%%, above) but barely moves what the\n' ...
        'network sees, because the fuel cell is a modest part of a net injection dominated\n' ...
        'by load, PV and battery. Stated plainly: on this profile PWL fidelity is a COST\n' ...
        'accuracy question, not a grid accuracy one. A grid-only study could use coarse PWL.\n' ...
        '\nAND THAT NOW SURVIVES A REAL TEST. The same comparison at the previous hub size\n' ...
        'was made by a hub at %.2f%% feeder penetration, where nothing the hub did could\n' ...
        'have moved a feeder-wide number; "indistinguishable" was close to guaranteed.\n' ...
        'This hub is %.2f%% of the feeder -- 4.7x larger -- and the two models STILL land\n' ...
        'within %.4f pu and %.1f kWh/day of each other. The conclusion was previously\n' ...
        'untestable and is now tested.\n'], ...
        min(relDel,relGate), max(relDel,relGate), ...
        2.79, sysNet.penetrationFeeder_pct, ...
        abs(NV{6}.minV - NV{5}.minV), abs(NV{6}.lossEnergy_kWh - NV{5}.lossEnergy_kWh));
else
    fprintf(['The two differ measurably at the grid level, so the modelling error does\n' ...
        'propagate: getting the part-load curve wrong changes what the network experiences,\n' ...
        'not only what the cost report says.\n']);
end

%% Seasonal case studies ----------------------------------------------
% Cases 1-4 above are the SHOULDER day. A multi-carrier hub is judged badly
% by one day, because heat demand and PV move in opposite directions across
% the year, so the whole comparison is repeated for winter and summer.
% 'shoulder' reproduces the profiles used above exactly, so those columns
% are the runs already computed rather than a re-solve, and the seasonal
% table is a strict extension of the result above it.
fprintf('\n=====================================================\n');
fprintf(' The same four cases, across three seasons\n');
fprintf('=====================================================\n');
fprintf(['Seasonal factors and their sourcing: season_profile_factors.m. Prices, emission\n' ...
    'factors and all equipment ratings are IDENTICAL across the three columns -- only the\n' ...
    'demand and PV profiles change, so differences below are seasonal physics and not a\n' ...
    'seasonal tariff.\n']);

seaList = {'winter', 'shoulder', 'summer'};
nSeaA   = numel(seaList);
seaCost = zeros(4, nSeaA); seaEmis = zeros(4, nSeaA); seaPeak = zeros(4, nSeaA);
seaMinV = zeros(4, nSeaA); seaLoss = zeros(4, nSeaA); seaFuel = zeros(1, nSeaA);
seaCapKW = zeros(1, nSeaA); seaUnmet = zeros(4, nSeaA); seaViol = zeros(4, nSeaA);
% Diagnostics for the ablation-reversal analysis further down: fuel and the
% cost split per case, plus how saturated the heat pump is, since that is
% what decides whether the fuel cell is the marginal HEAT source.
seaFuelCase = zeros(4, nSeaA); seaH2Cost = zeros(4, nSeaA); seaGridCost = zeros(4, nSeaA);
seaDAFuel = zeros(1, nSeaA); seaHPsat = zeros(1, nSeaA);
for k = 1:nSeaA
    if strcmp(seaList{k}, 'shoulder')
        fcK = fc;  CK = {C1, C2, C3, C4};                 % already solved above
    else
        fcK = forecast_profiles(42, 1.0, [], seaList{k});
        CK = {simulate_conventional_baseline(p, fcK), ...
              simulate_multiscale_day(p, fcK, struct('useIntraday', false, 'reserveScale', 1.0)), ...
              simulate_multiscale_day(p, fcK, struct('useIntraday', true,  'reserveScale', 0.0)), ...
              simulate_multiscale_day(p, fcK, struct('useIntraday', true,  'reserveScale', 1.0))};
    end
    seaCapKW(k) = feeder_capacity(p, fcK, 'design');
    seaFuel(k)  = sum(CK{4}.PH2_5)/12;
    seaDAFuel(k) = sum(CK{4}.DA.PH2);
    seaHPsat(k)  = sum(CK{4}.DA.Php > 0.999*p.HeatPump.Pmax);
    hourOf5K = ceil((1:288)/12)';
    pImp5 = fcK.DA.priceImport(hourOf5K); pExp5 = fcK.DA.priceExport(hourOf5K);
    for c = 2:4
        seaFuelCase(c,k)  = sum(CK{c}.PH2_5)/12;
        seaH2Cost(c,k)    = p.price_H2 * seaFuelCase(c,k);
        seaGridCost(c,k)  = sum(pImp5.*CK{c}.Pg_imp5 - pExp5.*CK{c}.Pg_exp5)/12;
    end
    for c = 1:4
        seaCost(c,k) = CK{c}.actualCost;
        seaEmis(c,k) = CK{c}.emissions_kgCO2;
        seaPeak(c,k) = max(CK{c}.Pg_imp5);
        nvK = network_verify(sysNet, CK{c}.Pg_imp5 - CK{c}.Pg_exp5);
        seaMinV(c,k) = nvK.minV;
        seaLoss(c,k) = nvK.lossEnergy_kWh;
        if c > 1
            % Same design-basis threshold logic as the shoulder table, but
            % recomputed per season because the connected load it is built
            % from is itself seasonal.
            vK = reliability_check(CK{c}.Pg_imp5, CK{c}.Pg_exp5, seaCapKW(k));
            seaUnmet(c,k) = vK.unmetEnergy_kWh;
            seaViol(c,k)  = vK.violationHours;
        end
    end
    seaBaseLoss = nvK.base_lossEnergy_kWh;
    seaBaseMinV = nvK.base_minV;
end

seaLabels = {'1: Conventional', '2: Day-ahead only', '3: No robust reserve', '4: Full proposed'};
metricSets = {seaCost, seaEmis, seaPeak, seaMinV, seaLoss};
metricName = {'Realized cost ($/day)', 'Emissions (kgCO2/day)', 'Peak grid import (kW)', ...
              'Exact min voltage (pu)', 'Feeder losses (kWh/day)'};
metricFmt  = {'%12.2f', '%12.1f', '%12.1f', '%12.4f', '%12.1f'};
for m = 1:numel(metricSets)
    fprintf('\n%s\n', metricName{m});
    fprintf('%-24s %12s %12s %12s\n', 'Case', 'winter', 'shoulder', 'summer');
    for c = 1:4
        fprintf(['%-24s ' metricFmt{m} ' ' metricFmt{m} ' ' metricFmt{m} '\n'], ...
            seaLabels{c}, metricSets{m}(c,:));
    end
end
fprintf('\nUnmet energy (kWh/day) / violation hours, against each season''s own design cap\n');
fprintf('%-24s %12s %12s %12s\n', 'Case', 'winter', 'shoulder', 'summer');
for c = 2:4
    fprintf('%-24s %5.2f /%5.2f %5.2f /%5.2f %5.2f /%5.2f\n', seaLabels{c}, ...
        seaUnmet(c,1), seaViol(c,1), seaUnmet(c,2), seaViol(c,2), seaUnmet(c,3), seaViol(c,3));
end
fprintf('%-24s %12.1f %12.1f %12.1f\n', 'Design cap (kW)', seaCapKW);
fprintf('\n%-24s %12.1f %12.1f %12.1f\n', 'FC fuel, Case 4 (kWh)', seaFuel);
fprintf('%-24s %12.4f %12s %12s\n', 'No-hub base min V (pu)', seaBaseMinV, '(same)', '(same)');
fprintf('%-24s %12.1f %12s %12s\n', 'No-hub base losses (kWh)', seaBaseLoss, '(same)', '(same)');

sav = 100*(seaCost(1,:) - seaCost(4,:)) ./ seaCost(1,:);
co2sav = 100*(seaEmis(1,:) - seaEmis(4,:)) ./ seaEmis(1,:);
fprintf('\n%-24s %11.1f%% %11.1f%% %11.1f%%\n', 'Case 4 vs 1 cost saving', sav);
fprintf('%-24s %11.1f%% %11.1f%% %11.1f%%\n', 'Case 4 vs 1 CO2 saving', co2sav);

fprintf(['\nTHE HEADLINE SAVING IS STRONGLY SEASONAL, and quoting the shoulder figure alone\n' ...
    'overstates it in winter and understates it in summer: %.1f%% / %.1f%% / %.1f%% on cost\n' ...
    'across winter / shoulder / summer. The mechanism is the PV-vs-heat anti-correlation.\n' ...
    'Case 1 burns gas for heat, so its cost tracks heat demand; Case 4 electrifies that\n' ...
    'heat and pays for it with PV that is at its annual minimum in exactly the season the\n' ...
    'heat is at its maximum. In summer the comparison inverts: almost no heat to serve and\n' ...
    'abundant PV, so the hub wins by its widest margin.\n' ...
    '\nSTATED PLAINLY BECAUSE IT QUALIFIES THIS PROJECT''S MOST-QUOTED NUMBER: the %.1f%%\n' ...
    'figure reported everywhere else is a SHOULDER-SEASON figure. An annual number would\n' ...
    'need weighting by season length, which this study does not do -- it reports three\n' ...
    'days, not a year, and the three days are not equally common.\n'], ...
    sav(1), sav(2), sav(3), sav(2));

% The ablation ORDERING is not seasonally stable either, and that is a
% harder result to report than the saving being seasonal, so it gets its own
% paragraph rather than a footnote.
ablate2 = 100*(seaCost(2,:) - seaCost(4,:)) ./ seaCost(4,:);
ablate3 = 100*(seaCost(3,:) - seaCost(4,:)) ./ seaCost(4,:);
fprintf('\n%-34s %10s %10s %10s\n', 'Ablation vs Case 4 (cost %)', 'winter', 'shoulder', 'summer');
fprintf('%-34s %+10.2f %+10.2f %+10.2f\n', 'Case 2 (no rolling layers)', ablate2);
fprintf('%-34s %+10.2f %+10.2f %+10.2f\n', 'Case 3 (no robust reserve)', ablate3);

if any(ablate2 < 0) || any(ablate3 < 0)
    dFuel = seaFuelCase(4,1) - seaFuelCase(2,1);
    dH2   = seaH2Cost(4,1)   - seaH2Cost(2,1);
    dGrid = seaGridCost(4,1) - seaGridCost(2,1);
    dCO2  = seaEmis(4,1)     - seaEmis(2,1);
    fprintf(['\nTHE ABLATIONS CHANGE SIGN IN WINTER, AND THAT IS THE MOST INCONVENIENT RESULT\n' ...
        'IN THIS TABLE. A positive number means removing the feature costs money, which is\n' ...
        'the claim the thesis makes for it. In winter Case 2 is %+.2f%% and Case 3 is\n' ...
        '%+.2f%%: THE FULL PROPOSED SYSTEM IS THE MOST EXPENSIVE OF THE THREE HUB CASES.\n' ...
        '\nIT IS NOT A SERVICE-LEVEL EFFECT. The obvious explanation -- that the cheaper\n' ...
        'cases are cheaper because they fail to serve load -- is FALSE here, and the table\n' ...
        'above says so: unmet energy is %.2f kWh in every winter case. All three meet the\n' ...
        'same demand.\n' ...
        '\nTHE MEASURED MECHANISM IS FUEL SUBSTITUTION, visible in the cost split:\n' ...
        '  the closed loop burns %+.1f kWh more hydrogen than the open loop (%+.2f $)\n' ...
        '  and saves %.2f $ of grid cost, for a net %+.2f $/day.\n' ...
        'The rolling layers commit MORE fuel cell than the day-ahead plan in both seasons\n' ...
        '-- winter %.0f kWh planned vs %.0f kWh realized, shoulder %.0f vs %.0f -- because\n' ...
        'each 15-minute solve sees one slot ahead and covers a heat shortfall locally\n' ...
        'instead of pre-charging thermal storage for it.\n' ...
        '\nWHETHER THAT PAYS DEPENDS ON HEAT-PUMP SATURATION, which is what makes the sign\n' ...
        'seasonal. In winter the heat pump runs at its full %.1f kW rating in %d of 24\n' ...
        'hours, so the fuel cell is the MARGINAL HEAT source: the extra hydrogen buys heat\n' ...
        'and displaces little grid electricity. On the shoulder day the heat pump is\n' ...
        'saturated in only %d of 24 hours, so the same extra fuel-cell output is mostly\n' ...
        'ELECTRICAL substitution during the expensive evening hours and pays for itself.\n' ...
        'Same mechanism, opposite sign, decided by whether the cheaper heat source is\n' ...
        'already flat out.\n' ...
        '\nAND THE CLOSED LOOP IS STILL CLEANER: %+.1f kgCO2/day in winter, because hydrogen\n' ...
        'at %.2f kgCO2/kWh is lower-carbon than grid electricity at %.2f. The winter\n' ...
        'reversal is a genuine COST-versus-CARBON trade, not a malfunction -- but a\n' ...
        'single-objective cost ablation cannot show that and scores it as a loss.\n' ...
        '\nTHREE HONEST CONCLUSIONS, ALL OF WHICH BELONG IN THE THESIS:\n' ...
        '  1. The +%.1f%%/+%.1f%% ablation figures quoted elsewhere are SHOULDER-SEASON\n' ...
        '     figures. They do not generalise across the year.\n' ...
        '  2. The value of rolling re-dispatch is conditional on WHICH constraint binds.\n' ...
        '     It pays when the binding problem is short-horizon (electrical forecast\n' ...
        '     error, what it was designed for) and costs money when the binding problem\n' ...
        '     is long-horizon (a tight heat balance needing 24-hour foresight, which a\n' ...
        '     2-slot horizon cannot supply).\n' ...
        '  3. A longer intraday horizon, or carrying the day-ahead heat schedule as a\n' ...
        '     harder constraint in winter, is the indicated fix. It is NOT implemented\n' ...
        '     here -- this session measured the defect rather than repairing it.\n'], ...
        ablate2(1), ablate3(1), seaUnmet(4,1), ...
        dFuel, dH2, -dGrid, dH2 + dGrid, ...
        seaDAFuel(1), seaFuel(1), seaDAFuel(2), seaFuel(2), ...
        p.HeatPump.Pmax, seaHPsat(1), seaHPsat(2), ...
        dCO2, p.co2.H2Factor, p.co2.gridFactor, ...
        ablate2(2), ablate3(2));
end

fprintf(['\nAnd the caveat that already travels with this number travels with all three\n' ...
    'columns unchanged: Case 1 owns no PV, battery, EV or heat pump at all, so most of\n' ...
    'every percentage above is the value of OWNING THE EQUIPMENT, not of the dispatch\n' ...
    'modelling this thesis contributes. The seasons change the size of that equipment\n' ...
    'effect; they do not turn it into a modelling result.\n']);

%% Plots
try
    figure('Position',[100 100 1000 700]);

    subplot(2,2,1);
    bar(cost); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('$/day'); title('Operational cost'); grid on;

    subplot(2,2,2);
    bar(emis); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('kgCO2/day'); title('Carbon emissions'); grid on;

    subplot(2,2,3);
    bar(peak); set(gca,'XTickLabel',{'1','2','3','4'});
    hold on; plot([0.5 4.5],[feederCap feederCap],'r--','LineWidth',1.2);
    ylabel('kW'); title('Peak grid import (dashed = feeder capacity for cases 2-4)'); grid on;

    subplot(2,2,4);
    bar([0 unmetE(2:4)]); set(gca,'XTickLabel',{'1','2','3','4'});
    ylabel('kWh/day'); title('Unmet energy (feeder-capacity violations)'); grid on;

    sgtitle_text = 'Case studies: 1=Conventional, 2=Day-ahead only, 3=No robust reserve, 4=Full proposed system';
    annotation('textbox',[0.05 0.95 0.9 0.05],'String',sgtitle_text,'EdgeColor','none','HorizontalAlignment','center','FontWeight','bold');
catch plot_err
    fprintf('\n[plots skipped: %s]\n', plot_err.message);
end
