%MAIN_MONTH4C_PWL_SEGMENT_SWEEP
%Thesis roadmap Month 4: segment-count trade-off for the fuel cell's PWL
%approximation, mirroring the accuracy-vs-computation table style used by
%Huang et al. (error% falling as segment count rises, at the cost of a
%larger MILP).
%
%   Sweeps p.PWL.nSegments in {1, 2, 5, 10, 20, 36} and reports, for each:
%     1) CURVE-FIT approximation error: the n-segment PWL fit vs. the
%        exact continuous efficiency function, evaluated over a dense
%        load-fraction grid (same methodology as Month 2's PWL-vs-
%        constant-efficiency error table: MaxErr/RMSE in kW), for BOTH
%        the fuel cell's electrical and thermal curves.
%     2) MILP SOLVE TIME: dayahead_dispatch.m's mean wall-clock solve
%        time at that segment count (mean of 5 solves), run at the
%        H2_doeTargetGate scenario ($0.06/kWh = $2.00/kg, DOE's 2026
%        production-gate target; see the three named scenarios in
%        multiscale_default_params.m).
%
%        WHY THE GATE PRICE HERE, when Case 5's headline uses the
%        like-for-like DELIVERED price instead: this is a CONVERGENCE
%        study, not an economic claim. The gate price is the cheapest of
%        the three and therefore maximises fuel-cell throughput (5 running
%        hours against 2 at the delivered price, and ~2.5x the fuel), which
%        puts the most energy through the nonlinear device and gives the
%        strongest, least noise-dominated signal for how approximation
%        error and solve time behave as segments are added. Choosing the
%        operating point that best exercises the thing being measured is
%        legitimate for a convergence study; it would NOT be legitimate
%        for the cost headline, which is why Case 5 reports both prices.
%        At the H2_today default the fuel cell is never dispatched at
%        all, so every segment count would solve a problem whose integer
%        variables are trivially zero and the sweep would measure nothing.
%     3) RESULTING COST: the day-ahead PLAN's own believed cost at that
%        segment count, and the REALIZED cost once the plan's fuel
%        purchase (PH2, unaffected by which curve interpretation is
%        used -- fuel is metered and priced independent of how
%        efficiently it converts) is re-evaluated through the EXACT
%        continuous efficiency function instead of the n-segment
%        approximation the day-ahead MILP believed. This isolates the
%        same "plan optimal for the wrong model" mechanism as Case 5,
%        but as a function of segment count rather than a single
%        PWL-vs-constant comparison point.
%
%   SCOPE NOTE: this re-evaluation only recomputes the ELECTRICAL side
%   (grid import/export adjust to cover the gap between the n-segment
%   model's believed fuel-cell electricity and the true nonlinear
%   output, holding storage/heat-pump/PV at their planned values). Any
%   heat-side mismatch from the true curve is NOT re-priced here -- the
%   full multi-timescale simulation (main_month4a_case_studies.m's Case
%   5) already shows that heat-side mismatches of this kind are small
%   and get absorbed by the building/pipe thermal storage's own inertia
%   without a fast correction (see realtime_balance.m's header); this
%   script is a static day-ahead-only sweep table, not a full closed-
%   loop re-simulation, so it is scoped to the dominant (electrical)
%   cost effect and says so rather than silently ignoring the rest.
%
%   Depends on Month 3's dispatch stack (../month3_multiscale_optimization).
%
%   Run with:  main_month4c_pwl_segment_sweep

clear; clc;
addpath('../month3_multiscale_optimization');

p = multiscale_default_params();
p.price_H2 = p.scenarios.H2_doeTargetGate;  % production-gate target: maximises FC
                                            % throughput, so the convergence signal is
                                            % clearest (see file header for why this is
                                            % the right choice HERE but not for Case 5's
                                            % cost headline).
fc = forecast_profiles(42);

% Extended to 150 to find where MILP tractability actually degrades. The
% thesis claims high-fidelity PWL *while retaining tractability*, and a
% sweep that stops at 36 never tests the second half of that claim. At
% n=150 the model carries 149 fill-order binaries per hour x 24 hours =
% 3576 binaries.
segCounts = [1, 2, 5, 10, 20, 36, 50, 75, 100, 150];
nS = numel(segCounts);

% Wall-clock budget per solve. A segment count that exceeds it is recorded
% as a RESULT ("exceeded budget"), not dropped as a missing row -- where
% the frontier lies is exactly what this sweep is for.
solveBudget_s = 300;

% Timing method: cheap counts keep the original mean-of-5 so the existing
% rows stay methodologically comparable; expensive ones are timed once,
% because 5 repeats of a 150-second solve would dominate the script for no
% extra information. Which method each row used is reported.
repeatThresh_s = 2.0;
nRepeats  = zeros(1,nS);
timedOut  = false(1,nS);

maxErrE = zeros(1,nS); rmseE = zeros(1,nS);
maxErrT = zeros(1,nS); rmseT = zeros(1,nS);
solveTime = zeros(1,nS);
plannedCost = zeros(1,nS);
realizedCost = zeros(1,nS);
optimism = zeros(1,nS);
netMinV      = zeros(1,nS);
netHrsBelow  = zeros(1,nS);
netLossEnergy = zeros(1,nS);
verifyTime   = zeros(1,nS);

% Network verification of each segment count's own dispatch, on the same
% IEEE 33 benchmark and the same ONE hub used everywhere else.
addpath('../month2_coupling_matrix_pwl_ieee33');
sysNet = ieee33_system_definition();

u_test = linspace(0.02, 1, 400);
x_test = u_test * p.PWL.FC_H2_max;
y_true_e = p.PWL.eta_FC_e_func(u_test)  .* x_test;
y_true_t = p.PWL.eta_FC_th_func(u_test) .* x_test;

fprintf('=====================================================\n');
fprintf(' PWL segment-count trade-off (fuel cell curves)\n');
fprintf('=====================================================\n');
fprintf(['Scenario H2_doeTargetGate: price_H2=$%.2f/kWh = $%.2f/kg (production gate).\n' ...
    'Chosen because it maximises fuel-cell throughput and so gives the clearest\n' ...
    'convergence signal -- see file header.\n\n'], ...
    p.price_H2, p.price_H2*p.scenarios.H2_kWhPerKg);

for i = 1:nS
    n = segCounts(i);
    pN = p;
    pN.PWL.nSegments = n;
    pN.PWL.bkpt_e  = pwl_utils('fit', p.PWL.eta_FC_e_func,  p.PWL.FC_H2_max, n, 'FC_elec_sweep');
    pN.PWL.bkpt_th = pwl_utils('fit', p.PWL.eta_FC_th_func, p.PWL.FC_H2_max, n, 'FC_heat_sweep');

    % 1) Curve-fit error vs. the exact continuous function
    y_pwl_e = pwl_utils('eval', pN.PWL.bkpt_e.x,  pN.PWL.bkpt_e.y,  x_test);
    y_pwl_t = pwl_utils('eval', pN.PWL.bkpt_th.x, pN.PWL.bkpt_th.y, x_test);
    errE = abs(y_true_e - y_pwl_e); errT = abs(y_true_t - y_pwl_t);
    maxErrE(i) = max(errE); rmseE(i) = sqrt(mean(errE.^2));
    maxErrT(i) = max(errT); rmseT(i) = sqrt(mean(errT.^2));

    % 2) MILP solve time. One solve first; repeat only if it was cheap.
    t0 = tic; sol = dayahead_dispatch(pN, fc); t1 = toc(t0);
    if t1 <= repeatThresh_s
        times = zeros(1,5); times(1) = t1;
        for r = 2:5
            t2 = tic; sol = dayahead_dispatch(pN, fc); times(r) = toc(t2);
        end
        solveTime(i) = mean(times); nRepeats(i) = 5;
    else
        solveTime(i) = t1; nRepeats(i) = 1;
    end
    timedOut(i) = (t1 > solveBudget_s);
    plannedCost(i) = sol.cost;
    fprintf('  n=%-4d solved in %8.3f s (%d sample(s))%s\n', n, solveTime(i), nRepeats(i), ...
        repmat(' *** EXCEEDED BUDGET ***', 1, timedOut(i)));
    fflush(stdout);

    % 3) Realized cost: re-evaluate the fuel cell's electrical output
    % through the EXACT continuous function, holding everything else at
    % its planned value, and let grid import/export absorb the gap.
    % fc_true_output clamps the solver's fuel vector at zero before touching
    % sqrt(); see its header for the complex-arithmetic failure that a raw
    % inline evaluation caused here.
    [FCelec_true, ~, PH2col] = fc_true_output(p, sol.PH2);
    FCelec_planned = pwl_utils('eval', pN.PWL.bkpt_e.x, pN.PWL.bkpt_e.y, PH2col);
    Pnet_new = (sol.Pg_imp(:) - sol.Pg_exp(:)) - (FCelec_true - FCelec_planned);
    % Safe now that Pnet_new is guaranteed real -- max(X,0) on a complex X
    % compares magnitudes, not real parts (see fc_true_output.m).
    Pgi_new = max(Pnet_new, 0); Pge_new = max(-Pnet_new, 0);
    realizedCost(i) = sum(fc.DA.priceImport(:).*Pgi_new - fc.DA.priceExport(:).*Pge_new) + p.price_H2*sum(PH2col);

    % 4) Optimism diagnostic (same definition as Case 5 in
    % main_month4a_case_studies.m): electricity this n-segment planning
    % model believed its own committed fuel would produce, minus what the
    % true curve really produces from that same fuel, per kW of fuel.
    % Reuses the two vectors already computed just above, so it adds no
    % new computation and cannot perturb any value in the table.
    %   > 0 optimistic  -> over-dispatches the FC -> reality under-delivers
    %                      -> Gap(%) pushed POSITIVE
    %   < 0 pessimistic -> Gap(%) pushed NEGATIVE
    optimism(i) = (sum(FCelec_planned) - sum(FCelec_true)) / sum(PH2col);

    % 5) Network verification of THIS segment count's dispatch. Uses the
    % REALIZED net injection (Pnet_new), i.e. after the true-curve
    % correction above -- that is what physically flows on the feeder,
    % not what the n-segment model believed would flow. Hourly steps here
    % because the sweep is day-ahead only.
    tic;
    nvI = network_verify(sysNet, Pnet_new, struct('dtHours', 1.0));
    verifyTime(i) = toc;
    netMinV(i)       = nvI.minV;
    netHrsBelow(i)   = nvI.hoursBelowLimit;
    netLossEnergy(i) = nvI.lossEnergy_kWh;
    if i == 1
        nvBase = nvI;   % base-case reference fields are identical across i
    end
end

fprintf('%-10s %10s %10s %10s %10s %12s %12s %12s %10s %10s\n', ...
    'nSegments', 'MaxErrE', 'RMSE-E', 'MaxErrT', 'RMSE-T', 'Solve(s)', 'Planned($)', 'Realized($)', 'Gap(%)', 'Optimism');
for i = 1:nS
    fprintf('%-10d %10.4f %10.4f %10.4f %10.4f %12.5f %12.4f %12.4f %10.2f %+10.4f\n', ...
        segCounts(i), maxErrE(i), rmseE(i), maxErrT(i), rmseT(i), solveTime(i), ...
        plannedCost(i), realizedCost(i), 100*(realizedCost(i)-plannedCost(i))/abs(plannedCost(i)), optimism(i));
end

%% Network consequences per segment count -----------------------------
fprintf(['\n--- Same sweep, verified on IEEE 33 (ONE hub at bus %d, %.2f%% of feeder load) ---\n' ...
    '(No voltage constraint is imposed in this sweep, so the unity-power-factor\n' ...
    ' tie-breaker holds Q at zero and these voltages are the pessimistic ones.)\n'], ...
    sysNet.hostBus, sysNet.penetrationFeeder_pct);
fprintf('%-10s %12s %12s %14s %12s %12s %8s\n', ...
    'nSegments', 'min V (pu)', 'hrs<0.95', 'losses kWh', 'MILP(s)', 'MILP+PF(s)', 'samples');
fprintf('%-10s %12.4f %12s %14.1f %12s %12s %8s\n', 'base', ...
    nvBase.base_minV, '24.00', nvBase.base_lossEnergy_kWh, '-', '-', '-');
for i = 1:nS
    if timedOut(i)
        fprintf('%-10d %12.4f %12.2f %14.1f %12s %12s %8d\n', segCounts(i), ...
            netMinV(i), netHrsBelow(i), netLossEnergy(i), 'OVER BUDGET', 'n/a', nRepeats(i));
    else
        fprintf('%-10d %12.4f %12.2f %14.1f %12.3f %12.3f %8d\n', segCounts(i), ...
            netMinV(i), netHrsBelow(i), netLossEnergy(i), ...
            solveTime(i), solveTime(i)+verifyTime(i), nRepeats(i));
    end
end
fprintf(['(samples = MILP solves timed: 5 where a single solve took under %.1f s, else 1.\n' ...
    ' Budget %.0f s per solve; a count exceeding it is reported as a result, not dropped.)\n'], ...
    repeatThresh_s, solveBudget_s);

%% Where the tractability wall falls -----------------------------------
fprintf('\n--- The accuracy / tractability frontier ---\n');
fprintf('%-10s %14s %14s %14s\n', 'nSegments', 'MaxErrE (kW)', 'MILP (s)', 'time x vs n=36');
i36 = find(segCounts == 36);
for i = 1:nS
    fprintf('%-10d %14.4f %14.3f %14.1f\n', segCounts(i), maxErrE(i), solveTime(i), ...
        solveTime(i)/solveTime(i36));
end

% Where does curve-fit error stop improving materially?
relGain = maxErrE(1:end-1) ./ maxErrE(2:end);   % factor improvement per step
iDimin = find(maxErrE < 0.10, 1, 'first');      % 0.1 kW on a 150 kW device = 0.07%
fprintf(['\nACCURACY SIDE. Curve-fit error falls steeply at first and then flattens in\n' ...
    'absolute terms: MaxErrE reaches %.4f kW at n=%d, i.e. below 0.1 kW on a %.0f kW\n' ...
    'device (under 0.1%% of rating). Beyond that the remaining error is far smaller than\n' ...
    'any physical uncertainty in the efficiency curve itself, so further segments buy\n' ...
    'precision the input data does not support.\n'], ...
    maxErrE(iDimin), segCounts(iDimin), p.PWL.FC_H2_max);

fprintf(['\nTRACTABILITY SIDE. Measured: n=36 %.2f s, n=50 %.2f s, n=75 %.2f s, n=100 %.2f s,\n' ...
    'n=150 %.2f s. Read the mid-range with care -- every count above n=36 is a SINGLE\n' ...
    'timed solve (see the samples column), so ordinary machine contention shows up\n' ...
    'directly and the 50/75/100 ordering is not stable between runs. What IS stable,\n' ...
    'because it dwarfs any plausible contention, is the final step: %.1f s to %.1f s,\n' ...
    'about %.0fx the time for 1.5x the segments, and %.0fx the n=36 baseline overall.\n' ...
    '\nThat is the wall, and the mechanism is not simply "more binaries". The binary count\n' ...
    'grows strictly linearly (%d fill-order binaries at n=150: 24 hours x 149), so a\n' ...
    'linear-cost solver would show a linear trend. Branch-and-bound does not: as segments\n' ...
    'narrow, each fill-order binary controls a thinner slice of fuel, the LP relaxation\n' ...
    'becomes a weaker guide to the integer optimum, and glpk explores disproportionately\n' ...
    'more nodes to prove optimality. Cost per segment is roughly constant; cost per SOLVE\n' ...
    'is not.\n' ...
    '\nBUT THE ABSOLUTE SECONDS ARE NOT A PROPERTY OF THE SEGMENT COUNT, AND THAT\n' ...
    'QUALIFIES THE CLAIM TWICE OVER.\n' ...
    '  ACROSS INSTANCES: the same sweep on the previous, smaller hub measured 169.1 s at\n' ...
    '  n=150 (145.8x the n=36 baseline); this hub measures %.1f s (%.0fx). The MILP is\n' ...
    '  structurally IDENTICAL -- same variables, same rows, same %d binaries -- and only\n' ...
    '  the NUMBERS in it differ, so that %.1fx difference comes from nothing but how hard\n' ...
    '  branch-and-bound finds this particular instance.\n' ...
    '  ACROSS RUNS OF THE SAME INSTANCE: three executions of THIS script, identical code\n' ...
    '  and identical data, returned 30.1 s, 36.3 s and 61.7 s at n=150 -- a 2x spread\n' ...
    '  from machine state alone. Every count above n=36 is a single timed solve, so that\n' ...
    '  variance lands directly on the number.\n' ...
    'The qualitative result -- superlinear growth, a knee somewhere above n=36 -- is\n' ...
    'robust and reproduces every time. The specific second count at n=150 is not, and it\n' ...
    'should not be quoted as a result.\n'], ...
    solveTime(i36), solveTime(segCounts==50), solveTime(segCounts==75), ...
    solveTime(segCounts==100), solveTime(segCounts==150), ...
    solveTime(segCounts==100), solveTime(segCounts==150), ...
    solveTime(segCounts==150)/solveTime(segCounts==100), ...
    solveTime(segCounts==150)/solveTime(i36), (150-1)*24, ...
    solveTime(segCounts==150), solveTime(segCounts==150)/solveTime(i36), (150-1)*24, ...
    169.1/solveTime(segCounts==150));

fprintf(['\nPRACTICAL BAND FOR THIS SYSTEM: roughly n=10 to n=36. Below 10 the cost error is\n' ...
    'material -- the n=1 row is wrong by %+.2f%% and n=2 by %+.2f%%; above ~36 the\n' ...
    'curve-fit error is already under %.2f kW and solve time starts climbing steeply for\n' ...
    'accuracy that no longer changes any reported number. n=5 (this project''s default)\n' ...
    'sits just below that band and is defensible for cost work; n=10-20 would be the\n' ...
    'conservative choice if solve time were free.\n' ...
    '\nHuang et al. report 30-70 as their practical band. This system''s band sits lower.\n' ...
    'That is NOT a reproduction of their result and should not be read as one -- different\n' ...
    'system, different curves, different price levels and a different solver. Only the\n' ...
    'shape of the trade-off is comparable, not the numbers.\n'], ...
    100*(realizedCost(1)-plannedCost(1))/abs(plannedCost(1)), ...
    100*(realizedCost(2)-plannedCost(2))/abs(plannedCost(2)), maxErrE(i36));

vSpread = max(netMinV) - min(netMinV);
lSpread = max(netLossEnergy) - min(netLossEnergy);
fprintf(['\nDOES FINER PWL CHANGE WHAT THE GRID EXPERIENCES, OR ONLY WHAT THE COST REPORT\n' ...
    'SAYS? Across the whole sweep, n=1 to n=36, minimum voltage moves %.4f pu and feeder\n' ...
    'loss energy moves %.1f kWh/day, while the curve-fit error falls by a factor of %.0f\n' ...
    '(MaxErrE %.4f -> %.4f kW) and the realized-cost gap swings from %+.2f%% to %+.2f%%.\n'], ...
    vSpread, lSpread, maxErrE(1)/maxErrE(end), maxErrE(1), maxErrE(end), ...
    100*(realizedCost(1)-plannedCost(1))/abs(plannedCost(1)), ...
    100*(realizedCost(end)-plannedCost(end))/abs(plannedCost(end)));

if vSpread < 5e-3 && lSpread < 50
    fprintf(['\nThe network outcomes are essentially INSENSITIVE to segment count, and that is\n' ...
        'reported as the finding rather than buried: the grid sees a %.4f pu voltage band and\n' ...
        'a %.1f kWh/day loss band across a 36-fold change in PWL fidelity. The mechanism is\n' ...
        'that segmentation changes how much HYDROGEN the fuel cell burns and how that is\n' ...
        'costed, but the resulting change in net grid injection is small next to the load,\n' ...
        'PV and battery flows that dominate it -- and feeder voltage responds to the net\n' ...
        'injection, not to how it was decided.\n' ...
        '\nPractical consequence, stated directly: a study whose question is about the GRID\n' ...
        'can use coarse PWL (even n=1) and get essentially the right network answer. Fine\n' ...
        'segmentation earns its keep on COST accuracy, which is where the coarse rows are\n' ...
        'wrong (%+.2f%% at n=1 and %+.2f%% at n=2, realized vs planned) even though their\n' ...
        'voltage and loss figures are indistinguishable from n=36''s. Accuracy in one metric\n' ...
        'does not imply accuracy in the other, and this sweep is the evidence for that\n' ...
        'claim.\n' ...
        '\nAND THIS ONE HAS NOW BEEN TESTED AT A SIZE WHERE IT COULD HAVE FAILED. The same\n' ...
        'sweep previously ran a hub at 2.79%% of feeder load, where no dispatch decision of\n' ...
        'any kind could have moved a feeder-wide number -- "segmentation does not change\n' ...
        'grid outcomes" was guaranteed by the hub''s size, not established by the sweep.\n' ...
        'This hub is %.2f%% of the feeder and the voltage band is %.4f pu. The finding was\n' ...
        'previously untestable and now survives a real test.\n'], ...
        vSpread, lSpread, ...
        100*(realizedCost(1)-plannedCost(1))/abs(plannedCost(1)), ...
        100*(realizedCost(2)-plannedCost(2))/abs(plannedCost(2)), ...
        sysNet.penetrationFeeder_pct, vSpread);
else
    fprintf(['\nNetwork outcomes DO move materially with segment count (%.4f pu, %.1f kWh/day\n' ...
        'across the sweep), so the accuracy/tractability trade-off is consistent across both\n' ...
        'cost and grid metrics: finer PWL buys a better answer to both questions.\n'], ...
        vSpread, lSpread);
end

fprintf(['\nTRUE COMPUTATIONAL COST of the IEEE-33-benchmarked study. The MILP(s) column is\n' ...
    'the optimisation alone; MILP+PF adds the %d exact power flows needed to verify each\n' ...
    'dispatch. Verification adds %.3f-%.3f s per segment count, so at n=36 the full\n' ...
    'benchmarked study costs %.3f s against %.3f s for the MILP alone (%.0f%% more). The\n' ...
    'network check is cheap relative to the MILP at high segment counts and dominates it\n' ...
    'at low ones -- worth knowing before scaling either up.\n'], ...
    numel(nvBase.steps), min(verifyTime), max(verifyTime), ...
    solveTime(end)+verifyTime(end), solveTime(end), 100*verifyTime(end)/solveTime(end));

% Slopes quoted in the explanation below, computed (not hardcoded) from the
% same fits used in the sweep. i1/i2/i10 locate the rows the text names by
% number, so the text stays correct if segCounts is ever edited.
slopeOf = @(n) diff(pwl_utils('fit', p.PWL.eta_FC_e_func, p.PWL.FC_H2_max, n, 's').y) ...
             ./ diff(pwl_utils('fit', p.PWL.eta_FC_e_func, p.PWL.FC_H2_max, n, 's').x);
slope1 = slopeOf(1); slope2 = slopeOf(2); slope5 = slopeOf(5);
i1 = find(segCounts == 1); i2 = find(segCounts == 2); i5 = find(segCounts == 5); i10 = find(segCounts == 10);
gapOf = @(i) 100*(realizedCost(i)-plannedCost(i))/abs(plannedCost(i));

fprintf(['\nCurve-fit error (Max/RMSE, kW) falls monotonically as segment count rises\n' ...
    '(nSegments=1 -> %d: MaxErrE %.4f -> %.4f kW, MaxErrT %.4f -> %.4f kW), the same\n' ...
    'qualitative shape as Huang et al.''s reported accuracy-vs-computation trend\n' ...
    '(13.7%%->8.35%%->1.11%%->0.06%% for their system/curves -- not the same numbers,\n' ...
    'same kind of trend). MILP solve time grows with segment count (more segment\n' ...
    'variables and fill-order binaries per hour), the tractability cost side of the\n' ...
    'trade-off the thesis is centrally about.\n' ...
    '\nThe Gap(%%) column CHANGES SIGN but converges in magnitude: %+.2f%% at n=1, %+.2f%% at\n' ...
    'n=2, %+.2f%% at n=5. The mechanism behind the sign is the OPTIMISM column, and it is\n' ...
    'exactly the same effect explained for Case 5 in main_month4a_case_studies.m. What\n' ...
    'matters is not how ACCURATE a coarse model is but whether it errs HIGH or LOW where\n' ...
    'the fuel cell actually operates:\n' ...
    '  n=1: chord slope %.4f, BELOW the true marginal slopes in the dispatched range\n' ...
    '       -> pessimistic (Optimism %+.4f) -> plans a high cost, reality beats the plan\n' ...
    '       -> gap pushed NEGATIVE (%+.2f%%).\n' ...
    '  n=2: one slope %.4f spanning the lower half of the range, vs the true curve''s own\n' ...
    '       %.4f over the first fifth of it; the true curve is convex there, so this chord\n' ...
    '       sits ABOVE it in between -> optimistic (Optimism %+.4f) -> over-dispatches the\n' ...
    '       fuel cell, reality then under-delivers -> gap pushed POSITIVE (%+.2f%%).\n' ...
    'Adding a segment improved the fit on every curve-fit metric AND flipped the sign of\n' ...
    'the modeling error. The sign of Optimism predicts the sign of Gap(%%) in every row of\n' ...
    'this table.\n' ...
    '\n*** CORRECTION TO A PREVIOUSLY REPORTED FINDING. Earlier versions of this study\n' ...
    'reported the n=2 row at +24.80%%, called it a "genuine outlier -- worse than n=1", and\n' ...
    'built an explanation on top of it. That number was a BUG, not a result. The fuel cell\n' ...
    'is idle in most hours and the LP returns -1.19e-13 rather than 0 for one of them;\n' ...
    'sqrt() of a negative makes the true-curve evaluation COMPLEX, and Octave''s max(X,0)\n' ...
    'compares MAGNITUDES for complex X, so the idiom that splits net exchange into import\n' ...
    'and export returned a NEGATIVE import at hour 22 and priced a 4.4 kWh export as a\n' ...
    '4.4 kWh import. 23.35 of those 24.80 percentage points were arithmetic. The corrected\n' ...
    'value is %+.2f%%, |gap| now falls monotonically with segment count, and n=2 is NOT an\n' ...
    'outlier. What survives is the part that was actually load-bearing: the SIGN of\n' ...
    'Optimism still predicts the sign of Gap in every row. See fc_true_output.m. ***\n' ...
    '\nMAGNITUDE STILL IS NOT CLAIMED TO SCALE: n=1 has by far the largest |Optimism|\n' ...
    '(%+.4f) and also the largest |gap|, but n=2''s |Optimism| is %.0fx smaller while its\n' ...
    '|gap| is only %.1fx smaller. A shortfall must be covered by importing at\n' ...
    '$%.2f-$%.2f/kWh whereas a surplus is only worth the $%.2f/kWh export price, so\n' ...
    'optimism is punished harder than pessimism is rewarded, and the re-dispatch itself\n' ...
    'differs per row. Read Optimism as a direction, not a magnitude.\n' ...
    '\nThis is why the CURVE-FIT ERROR columns, not the gap, are the decision-independent\n' ...
    'measure of PWL accuracy: they depend only on the approximation, whereas the gap also\n' ...
    'depends on which dispatch that approximation happened to induce. By nSegments=10 both\n' ...
    'have converged -- Optimism is within %+.4f of neutral and the gap within %.2f%% of\n' ...
    'zero.\n'], segCounts(end), maxErrE(1), maxErrE(end), maxErrT(1), maxErrT(end), ...
    gapOf(i1), gapOf(i2), gapOf(i5), ...
    slope1(1), optimism(i1), gapOf(i1), ...
    slope2(1), slope5(1), optimism(i2), gapOf(i2), ...
    gapOf(i2), ...
    optimism(i1), abs(optimism(i1)/optimism(i2)), abs(gapOf(i1)/gapOf(i2)), ...
    min(fc.DA.priceImport), max(fc.DA.priceImport), max(fc.DA.priceExport), ...
    optimism(i10), abs(gapOf(i10)));

%% Plot
try
    % Shared annotation: the shipped default and the practical band that
    % VALIDATION.md concludes from this very sweep ("n = 10 to n = 36").
    % Drawn on all four panels so a reader sees at once where the chosen
    % count sits relative to the evidence that justifies it.
    nDef = 10; bandLo = 10; bandHi = 36;
    function mark_default(xIsIndex, segCounts, nDef, bandLo, bandHi)
        yl = ylim();
        if xIsIndex
            xd  = find(segCounts == nDef, 1);
            xlo = find(segCounts == bandLo, 1); xhi = find(segCounts == bandHi, 1);
        else
            xd = nDef; xlo = bandLo; xhi = bandHi;
        end
        if isempty(xd) || isempty(xlo) || isempty(xhi); return; end
        hold on;
        % Drawn without uistack, which is absent in some Octave builds and
        % silently sent this whole figure into its catch block. A translucent
        % band over the existing lines reads the same and needs no restacking.
        patch([xlo xhi xhi xlo], [yl(1) yl(1) yl(2) yl(2)], [0.85 0.92 0.98], ...
              'EdgeColor','none', 'FaceAlpha', 0.25, 'HandleVisibility','off');
        plot([xd xd], yl, 'r--', 'LineWidth', 1.6, 'HandleVisibility','off');
        % Labels placed INSIDE the axes and away from the frame: the first
        % version put the band caption at the bottom-left corner, nowhere near
        % the band it described, and the n=10 label on top of the axis line.
        % Positions are interpolated in the axis's OWN scale. On the log panel
        % a linear fraction of (max-min) lands both labels against the top
        % frame, where they overprinted each other.
        if strcmp(get(gca,'YScale'), 'log')
            yat = @(fr) 10.^(log10(yl(1)) + fr*(log10(yl(2)) - log10(yl(1))));
        else
            yat = @(fr) yl(1) + fr*(yl(2) - yl(1));
        end
        text(xd, yat(0.94), sprintf(' n=%d (shipped)', nDef), 'Color','r', ...
             'VerticalAlignment','top', 'HorizontalAlignment','left', 'FontSize', 8);
        text((xlo+xhi)/2, yat(0.80), sprintf('practical band n=%d-%d', bandLo, bandHi), ...
             'HorizontalAlignment','center', 'VerticalAlignment','top', 'FontSize', 8);
        ylim(yl);
        hold off;
    end

    figure('Position',[100 100 1000 700]);

    subplot(2,2,1);
    semilogy(segCounts, maxErrE, '-o', 'DisplayName','Electrical'); hold on;
    semilogy(segCounts, maxErrT, '-s', 'DisplayName','Thermal'); grid on;
    xlabel('nSegments'); ylabel('Max curve-fit error (kW)'); legend('Location','northeast');
    title('PWL approximation error vs. segment count');
    mark_default(false, segCounts, nDef, bandLo, bandHi);

    subplot(2,2,2);
    plot(segCounts, solveTime, '-o'); grid on;
    xlabel('nSegments'); ylabel('Mean MILP solve time (s)');
    title('Day-ahead MILP solve time vs. segment count');
    mark_default(false, segCounts, nDef, bandLo, bandHi);

    subplot(2,2,3);
    plot(segCounts, plannedCost, '-o', 'DisplayName','Planned'); hold on;
    plot(segCounts, realizedCost, '-s', 'DisplayName','Realized'); grid on;
    xlabel('nSegments'); ylabel('Cost ($/day)'); legend('Location','northeast');
    title('Planned vs. realized day-ahead cost');
    mark_default(false, segCounts, nDef, bandLo, bandHi);

    subplot(2,2,4);
    bar(100*(realizedCost-plannedCost)./abs(plannedCost));
    set(gca,'XTickLabel',arrayfun(@num2str,segCounts,'UniformOutput',false));
    xlabel('nSegments'); ylabel('Gap (%)'); grid on;
    title('Realized-vs-planned cost gap vs. segment count');
    % PANEL 4 IS CATEGORICAL. bar() places bars at 1..10 and the tick LABELS
    % carry the segment counts, so drawing the marker at data coordinate 10
    % put it on the tenth BAR (n=150) instead of on n=10. mark_default is
    % called with xIsIndex=true so it maps through find(segCounts==...).
    mark_default(true, segCounts, nDef, bandLo, bandHi);
    % The n=2 anomaly, annotated from the LIVE sweep values rather than from a
    % remembered constant: every curve-fit metric improves from n=1 to n=2 and
    % the realized-cost gap gets WORSE, purely because the modelling error
    % flips from pessimistic to optimistic.
    gapsPct = 100*(realizedCost-plannedCost)./abs(plannedCost);
    i2p = find(segCounts == 2, 1); i1p = find(segCounts == 1, 1);
    if ~isempty(i2p) && ~isempty(i1p)
        hold on;
        % Placed to the RIGHT of the n=2 bar with a leader line. The first
        % version anchored the text at the bar itself, where it collided with
        % the y-axis and was unreadable.
        % Anchored well clear of both the bar and the right-hand frame, with a
        % short leader. Earlier placements collided with the y-axis, then ran
        % off the right edge; the text is now shorter and left-anchored at a
        % slot with empty space above it.
        % Parked in the empty upper-right of the panel with a leader back to
        % the n=2 bar. Two earlier placements -- at the bar, then just beside
        % it -- collided with the y-axis and then with the bars themselves.
        yl4 = ylim(); yr4 = yl4(2) - yl4(1);
        ylim([yl4(1), yl4(2) + 0.55*yr4]);
        yl4 = ylim();
        tx = numel(segCounts) * 0.55; ty = yl4(2) - 0.06*(yl4(2)-yl4(1));
        plot([i2p tx], [gapsPct(i2p) ty], 'k-', 'LineWidth', 0.7, 'HandleVisibility','off');
        % SINGLE-LINE text: the gnuplot backend places multi-line text at the
        % axes origin rather than at the requested coordinates, so a three-line
        % caption rendered on top of the bars. Two shorter lines are issued as
        % two separate text() calls instead, which the backend does honour.
        text(tx, ty, sprintf(' n=2 (%+.2f%%) is WORSE than n=1 (%+.2f%%)', ...
             gapsPct(i2p), gapsPct(i1p)), 'FontSize', 8, ...
             'VerticalAlignment','top', 'HorizontalAlignment','left');
        text(tx, ty - 0.075*(yl4(2)-yl4(1)), ' despite the better fit: the chord turns OPTIMISTIC', ...
             'FontSize', 8, 'VerticalAlignment','top', 'HorizontalAlignment','left');
        hold off;
    end
catch plot_err
    fprintf('\n[plots skipped: %s]\n', plot_err.message);
end
