function mc_report_month4j(S)
%MC_REPORT_MONTH4J Tables and verdicts for the Month 4j per-device PWL study.
%
%   Extracted VERBATIM from main_month4j_pwl_device_table.m so the
%   single-process path and the chunked path print from ONE implementation.
%   Any difference between the two runs is then necessarily a difference in
%   the per-draw data, which is what the equivalence test checks.

    thisFile = mfilename('fullpath');
    addpath(fileparts(thisFile));
    addpath(fullfile(fileparts(thisFile), '..', 'month3_multiscale_optimization'));
    p = S.p; nDraw = S.nDraw; nCfg = S.nCfg; cfg = S.cfg;
    priceCases = S.priceCases; seasons = S.seasons; drawSeason = S.drawSeason;
    costP = S.costP; co2P = S.co2P; tsolveP = S.tsolveP;
    fcThruP = S.fcThruP; hpThruP = S.hpThruP;
    pHPon = S.pHPon; pHPoff = S.pHPoff;

nBinFC = (p.PWL.nSegments - 1) * 24;
nBinHP = (p.HeatPump.nSegments - 1) * 24;
binCount = [0, nBinFC, nBinHP, nBinFC + nBinHP];
Sall = cell(1, numel(priceCases));

for ip = 1:numel(priceCases)
cost = costP{ip}; co2 = co2P{ip}; tsolve = tsolveP{ip};
fprintf('\n\n#####################################################\n');
fprintf(' PRICE CASE %d: %s ($%.2f/kg) -- mean fuel-cell throughput %.0f kWh/day\n', ...
    ip, priceCases(ip).label, priceCases(ip).price*p.scenarios.H2_kWhPerKg, fcThruP(ip));
fprintf('#####################################################\n');

%% Main table -----------------------------------------------------------
fprintf('\n=====================================================\n');
fprintf(' Pooled over all %d draws\n', nDraw);
fprintf('=====================================================\n');
fprintf('%-40s %10s %10s %9s %9s %10s %18s  %s\n', 'Configuration', 'Cost($/d)', 'CO2(kg)', ...
    'Solve(s)', 'Binaries', 'Benefit%', '95% CI', 'Distinguishable?');
S = cell(1, nCfg);
for c = 1:nCfg
    if c == 1
        fprintf('%-40s %10.2f %10.1f %9.3f %9d %10s %18s  %s\n', cfg(c).label, ...
            mean(cost(:,1)), mean(co2(:,1)), mean(tsolve(:,1)), binCount(1), ...
            '-- ref --', '--', '--');
    else
        d = 100*(cost(:,1) - cost(:,c)) ./ cost(:,c);   % + = this config is cheaper
        S{c} = paired_stats(d, true);
        if S{c}.distinguishable && S{c}.bootDistinguishable && S{c}.signSignificant
            verd = 'YES';
        elseif S{c}.signOpposite && S{c}.distinguishable
            verd = 'YES, but NEGATIVE';
        else
            verd = 'no';
        end
        fprintf('%-40s %10.2f %10.1f %9.3f %9d %10.3f [%+7.3f,%+7.3f]  %s\n', cfg(c).label, ...
            mean(cost(:,c)), mean(co2(:,c)), mean(tsolve(:,c)), binCount(c), ...
            S{c}.mean, S{c}.ciLo, S{c}.ciHi, verd);
    end
end
fprintf('%-40s %10s %10s %9s %9s %10s %18s  %s\n', '+ PV inverter PWL', 'NOT RUN', '--', '--', '--', '--', '--', 'gate not passed');
fprintf('%-40s %10s %10s %9s %9s %10s %18s  %s\n', '+ battery PWL',      'NOT RUN', '--', '--', '--', '--', '--', 'gate not passed');

%% Per season -----------------------------------------------------------
fprintf('\n--- Benefit vs all-constant, per season (%%, + = PWL config cheaper) ---\n');
fprintf('%-40s %22s %22s %22s\n', 'Configuration', 'winter', 'shoulder', 'summer');
for c = 2:nCfg
    fprintf('%-40s', cfg(c).label);
    for sIdx = 1:numel(seasons)
        sel = strcmp(drawSeason, seasons{sIdx});
        st  = paired_stats(100*(cost(sel,1) - cost(sel,c)) ./ cost(sel,c), true);
        fprintf(' %7.3f [%+6.3f,%+6.3f]', st.mean, st.ciLo, st.ciHi);
    end
    fprintf('\n');
end

%% Marginal contributions -----------------------------------------------
fprintf('\n=====================================================\n');
fprintf(' MARGINAL contribution of each device\n');
fprintf('=====================================================\n');
fprintf('The benefit of ADDING that device''s PWL to the configuration above it,\n');
fprintf('so a reader can see which device carries the effect and which is noise.\n\n');
marg = { 'fuel cell PWL, added to all-constant',            1, 2; ...
         'heat pump PWL, added to fuel-cell PWL',           2, 4; ...
         'heat pump PWL, added to all-constant',            1, 3; ...
         'fuel cell PWL, added to heat-pump PWL',           3, 4 };
fprintf('%-42s %9s %9s %18s %8s  %s\n', 'Marginal step', 'mean %', 'median', '95% CI (t)', 'sign+', 'verdict');
for m = 1:size(marg,1)
    a = marg{m,2}; b = marg{m,3};
    st = paired_stats(100*(cost(:,a) - cost(:,b)) ./ cost(:,b), true);
    fprintf('%-42s %9.3f %9.3f [%+8.3f,%+7.3f] %4d/%-3d  %s\n', marg{m,1}, ...
        st.mean, st.median, st.ciLo, st.ciHi, st.nAgree, st.nNonZero, st.verdict);
end

fprintf('\n--- Same marginal steps, per season ---\n');
fprintf('%-42s %20s %20s %20s\n', 'Marginal step', 'winter', 'shoulder', 'summer');
for m = 1:size(marg,1)
    a = marg{m,2}; b = marg{m,3};
    fprintf('%-42s', marg{m,1});
    for sIdx = 1:numel(seasons)
        sel = strcmp(drawSeason, seasons{sIdx});
        st  = paired_stats(100*(cost(sel,a) - cost(sel,b)) ./ cost(sel,b), true);
        fprintf(' %6.3f [%+5.2f,%+5.2f]', st.mean, st.ciLo, st.ciHi);
    end
    fprintf('\n');
end


Sall{ip} = S;
end
S = Sall{1};
cost = costP{1};

%% Throughput, curvature, and the rule ----------------------------------
fprintf('\n\n=====================================================\n');
fprintf(' What actually predicts whether PWL pays\n');
fprintf('=====================================================\n');
fcRef = forecast_profiles(42, 1.0, [], 'shoulder');
hpRef = heatpump_curve(pHPon, fcRef.ambientC);
fcSl   = diff(p.PWL.bkpt_e.y) ./ diff(p.PWL.bkpt_e.x);
fcCurv = (max(fcSl)-min(fcSl))/mean(fcSl);
hpCurv = (max(hpRef.slopes)-min(hpRef.slopes))/mean(hpRef.slopes);

fcLo = Sall{1}{2}; fcHi = Sall{2}{2};      % fuel cell, both price cases
hpLo = Sall{1}{3}; hpHi = Sall{2}{3};      % heat pump, both price cases

% CURVATURE is the spread of the segment slopes normalised by their mean --
% how much the efficiency actually varies across the operating range. It is a
% property of the curve alone and does not depend on the price case.
fprintf('\n--- The two candidate predictors, both on the same 60-draw basis ---\n');
fprintf('%-14s %11s %11s %10s %11s %11s\n', 'device', ...
    'thru today', 'thru targ', 'curvature', 'txc today', 'txc targ');
fprintf('%-14s %7.0f kWh %7.0f kWh %10.3f %11.0f %11.0f\n', 'fuel cell', ...
    fcThruP(1), fcThruP(2), fcCurv, fcThruP(1)*fcCurv, fcThruP(2)*fcCurv);
fprintf('%-14s %7.0f kWh %7.0f kWh %10.3f %11.0f %11.0f\n', 'heat pump', ...
    hpThruP(1), hpThruP(2), hpCurv, hpThruP(1)*hpCurv, hpThruP(2)*hpCurv);
fprintf('%-14s %7.0f kWh %7s %10s %11s %11s\n', 'PV inverter', ...
    sum(fcRef.DA.solar), 'n/a', 'n/a', 'n/a', 'n/a');

fprintf('\n--- What each device''s PWL is worth, and how it comes to be dispatched ---\n');
fprintf('%-14s %11s %24s %11s %24s\n', 'device', ...
    'dispatch@today', 'PWL benefit, H2 today', 'dispatch@targ', 'PWL benefit, H2 target');
fprintf('%-14s %11s %9.3f%% [%+6.2f,%+6.2f] %11s %9.3f%% [%+6.2f,%+6.2f]\n', 'fuel cell', ...
    'must-run', fcLo.mean, fcLo.ciLo, fcLo.ciHi, ...
    'economic', fcHi.mean, fcHi.ciLo, fcHi.ciHi);
fprintf('%-14s %11s %9.3f%% [%+6.2f,%+6.2f] %11s %9.3f%% [%+6.2f,%+6.2f]\n', 'heat pump', ...
    'economic', hpLo.mean, hpLo.ciLo, hpLo.ciHi, ...
    'economic', hpHi.mean, hpHi.ciLo, hpHi.ciHi);
fprintf('%-14s %11s %24s %11s %24s\n', 'PV inverter', ...
    'n/a', 'NOT RUN -- gate not passed', 'n/a', 'NOT RUN -- gate not passed');

fprintf(['\nTHROUGHPUT ALONE DOES NOT PREDICT IT, and the table above is the evidence.\n' ...
    'The heat pump moves %.0f kWh/day against the fuel cell''s %.0f at today''s price --\n' ...
    '%.1fx more -- and its PWL benefit does not resolve in either price case. A rule of\n' ...
    'the form "PWL pays above X kWh/day throughput" would have predicted the heat pump\n' ...
    'as the stronger candidate. It is the weaker one.\n' ...
    ''], hpThruP(1), fcThruP(1), hpThruP(1)/max(fcThruP(1),1e-9));

% Does throughput x curvature order the four device-x-price cells? CHECKED
% IN CODE rather than asserted, because the corrected numbers do not give
% the clean answer an earlier draft of this file claimed.
cellName = {'FC @today', 'FC @target', 'HP @today', 'HP @target'};
cellTxc  = [fcThruP(1)*fcCurv, fcThruP(2)*fcCurv, hpThruP(1)*hpCurv, hpThruP(2)*hpCurv];
cellBen  = [fcLo.mean, fcHi.mean, hpLo.mean, hpHi.mean];
cellRes  = [fcLo.distinguishable, fcHi.distinguishable, ...
            hpLo.distinguishable, hpHi.distinguishable];
[~, ord] = sort(cellTxc);
fprintf('\n--- Ranked by throughput x curvature, lowest first ---\n');
fprintf('%-12s %13s %12s  %s\n', 'cell', 'thru x curv', 'benefit %', 'resolved?');
for q = ord(:)'
    if cellRes(q); rs = 'yes'; else; rs = 'no (spans zero)'; end
    fprintf('%-12s %13.0f %12.3f  %s\n', cellName{q}, cellTxc(q), cellBen(q), rs);
end
benOrd = cellBen(ord);
if all(diff(benOrd) > 0); monoTxt = 'YES'; else; monoTxt = 'NO'; end
fprintf('Monotone in benefit across all four cells? %s\n', monoTxt);

fprintf(['\nTHROUGHPUT x CURVATURE DOES NOT ORDER ALL FOUR CELLS, and an earlier draft of\n' ...
    'this file claimed it did. The ranking above is not monotone: the heat pump''s two\n' ...
    'cells sit in the middle and run the WRONG WAY round each other -- its product FALLS\n' ...
    'from %.0f to %.0f while its benefit RISES from %+.3f%% to %+.3f%%.\n' ...
    '\nThe honest reading is narrower. Only TWO of the four cells resolve, and both are\n' ...
    'the fuel cell''s: the lowest product (%.0f) gives a resolved NEGATIVE and the highest\n' ...
    '(%.0f) a resolved POSITIVE, with the two heat-pump cells unresolved in between. That\n' ...
    'is CONSISTENT with the product mattering, and it is two points -- far too thin to\n' ...
    'call an ordering law. The non-monotonicity sits entirely inside the unresolved pair,\n' ...
    'so it does not refute the hypothesis either. It is simply not settled by this data,\n' ...
    'and reporting it as settled would be the error this session exists to avoid.\n' ...
    '\nWHY THE HEAT PUMP''S THROUGHPUT FALLS when hydrogen gets CHEAPER (%.0f -> %.0f\n' ...
    'kWh/day) is worth naming, because it is the displacement mechanism this project\n' ...
    'already documents elsewhere: at $2.93/kg the fuel cell runs hard and its WASTE HEAT\n' ...
    'covers demand the heat pump would otherwise serve. The two devices compete for one\n' ...
    'heat load, so throughput is NOT a fixed property of a device -- it is set by the\n' ...
    'price regime. That alone disqualifies throughput as a design-time screening rule,\n' ...
    'independently of anything the confounding below adds.\n' ...
    '\nWHAT IS SOLID ABOUT CURVATURE: the heat pump''s is %.2f against the fuel cell''s\n' ...
    '%.2f -- %.1fx LESS curved, not comparably curved as that earlier draft said. Its COP\n' ...
    'varies by a factor of %.2f across the range while the fuel cell''s electrical\n' ...
    'efficiency varies by %.2f. Whatever else is unsettled, the heat pump is the FLATTER\n' ...
    'device, and a flatter curve leaves less for extra segments to capture.\n'], ...
    hpThruP(1)*hpCurv, hpThruP(2)*hpCurv, hpLo.mean, hpHi.mean, ...
    min(cellTxc), max(cellTxc), hpThruP(1), hpThruP(2), ...
    hpCurv, fcCurv, fcCurv/max(hpCurv,1e-9), ...
    max(hpRef.slopes)/min(hpRef.slopes), max(fcSl)/min(fcSl));

fprintf(['\nBUT IT CANNOT BE SEPARATED FROM DISPATCH FREEDOM IN THIS DATA, AND SAYING SO\n' ...
    'MATTERS MORE THAN CLAIMING THE RULE. The fuel cell''s two rows differ ONLY in the\n' ...
    'hydrogen price, and that one change moves TWO things at once:\n' ...
    '  at $7.33/kg it runs %.0f kWh/day, and only because the winter heat balance forces\n' ...
    '  it -- MUST-RUN operation, where the operating point is dictated rather than\n' ...
    '  chosen. PWL benefit: %+.3f%% [%+.2f, %+.2f]. Negative, and resolved.\n' ...
    '  at $2.93/kg it runs %.0f kWh/day -- %.0fx more -- and picks its own operating\n' ...
    '  point. PWL benefit: %+.3f%% [%+.2f, %+.2f]. Positive, and resolved.\n' ...
    'Throughput and scheduling freedom are therefore PERFECTLY CONFOUNDED across those\n' ...
    'two rows, and no experiment in this session separates them. "Throughput x curvature"\n' ...
    'and "the optimizer must be choosing the operating point" fit this data equally well.\n' ...
    'Separating them would need a run that raises throughput while KEEPING the device\n' ...
    'must-run -- a larger winter heat deficit at today''s price would do it -- and that\n' ...
    'is stated here as the missing experiment rather than papered over.\n' ...
    '\nWHAT THE TWO ROWS DO ESTABLISH BEYOND DOUBT is narrower and still worth having:\n' ...
    'the SAME device, the SAME curve, the SAME segment count and the SAME binaries show\n' ...
    'a resolved POSITIVE or a resolved NEGATIVE PWL benefit depending only on the price\n' ...
    'regime it is dispatched under. So "we applied PWL" is not by itself a statement\n' ...
    'about anything, which is the claim this session set out to test.\n'], ...
    fcThruP(1), fcLo.mean, fcLo.ciLo, fcLo.ciHi, ...
    fcThruP(2), fcThruP(2)/max(fcThruP(1),1e-9), fcHi.mean, fcHi.ciLo, fcHi.ciHi);

fprintf(['\nTHE DECISION RULE THE DATA SUPPORTS -- four conditions, all necessary:\n' ...
    '  1. THROUGHPUT x CURVATURE. The device must move enough energy AND its efficiency\n' ...
    '     must actually vary over the range. Throughput alone is not sufficient: the\n' ...
    '     heat pump moves the most energy of the two modelled devices and never resolves.\n' ...
    '     NECESSARY, NOT SHOWN TO BE ORDERING: the product does not rank the four cells\n' ...
    '     monotonically, as the ranking above reports. Treat it as a screen, not a score.\n' ...
    '  2. SCHEDULING FREEDOM. The optimizer must be able to CHOOSE the operating point.\n' ...
    '     A must-run device gets no benefit from a better curve because it is not\n' ...
    '     choosing anything, and the extra segments then only add ways to be wrong --\n' ...
    '     measured here as a resolved NEGATIVE. STATED AS A CONDITION, NOT AS A PROVEN\n' ...
    '     ONE: this data cannot separate it from condition 1, as set out above.\n' ...
    '  3. OPERATING RANGE. The device must move across several segments. One parked\n' ...
    '     inside a single segment gets nothing from the other four, and if that segment\n' ...
    '     is the coarsest part of the fit it is actively worse off. The heat pump in\n' ...
    '     summer sits at ~13%% load, 70%% of its running time inside segment 1, and its\n' ...
    '     PWL benefit there is %+.3f%% [%+.2f, %+.2f] -- a reliable cost.\n' ...
    '  4. ERROR DIRECTION. The fit must err PESSIMISTICALLY where the device operates.\n' ...
    '     Optimism and pessimism are not symmetric in cost: a shortfall is covered at\n' ...
    '     the import tariff, a surplus is only worth the export price. This is the same\n' ...
    '     asymmetry the Optimism column in Month 4a established for the fuel cell,\n' ...
    '     reappearing on a second device -- which is what makes it a mechanism rather\n' ...
    '     than a coincidence.\n' ...
    '\nConditions 3 and 4 are about BREAKPOINT PLACEMENT, and main_month4i tested\n' ...
    'whether placement alone rescues the heat pump. IT DOES NOT: curvature-placed\n' ...
    'breakpoints on the same segment count give -0.137%% [-0.580, +0.307], still\n' ...
    'spanning zero, and are WORSE than uniform in summer. They are the better FIT --\n' ...
    'the summer error moves from +1.46 kW optimistic to -0.70 kW pessimistic -- and\n' ...
    'still the worse COST. A closer fit does not automatically buy a cheaper dispatch,\n' ...
    'so an argument for PWL that reasons from approximation error alone is incomplete.\n' ...
    '\nPRACTICAL FORM: before spending binaries on a device, ask whether the optimizer\n' ...
    'chooses its operating point, where on the curve it operates, and whether the fit\n' ...
    'errs high there. Segment count is the last thing to tune, not the first.\n'], ...
    paired_stats(100*(costP{1}(strcmp(drawSeason,'summer'),1) - costP{1}(strcmp(drawSeason,'summer'),3)) ...
        ./ costP{1}(strcmp(drawSeason,'summer'),3), true).mean, ...
    paired_stats(100*(costP{1}(strcmp(drawSeason,'summer'),1) - costP{1}(strcmp(drawSeason,'summer'),3)) ...
        ./ costP{1}(strcmp(drawSeason,'summer'),3), true).ciLo, ...
    paired_stats(100*(costP{1}(strcmp(drawSeason,'summer'),1) - costP{1}(strcmp(drawSeason,'summer'),3)) ...
        ./ costP{1}(strcmp(drawSeason,'summer'),3), true).ciHi);

fprintf(['\nA NOTE ON MONTH 4e, so the two are not read as contradicting each other. Month\n' ...
    '4e measured the fuel cell''s PWL benefit at +1.42%% on the delivered-target price;\n' ...
    'this table gives %+.2f%% for the same comparison. The difference is the THERMAL\n' ...
    'correction described in this file''s header, which Month 4e did not apply -- the\n' ...
    'constant-efficiency comparator over-promises heat and was not being charged for it.\n' ...
    'Both numbers are positive and resolved; this one is the more complete accounting.\n'], ...
    fcHi.mean);

fprintf(['\nWHAT THIS TABLE DOES NOT SETTLE, stated so it is not over-read: it measures\n' ...
    'COST under one tariff structure, on three representative days, at one hub size. It\n' ...
    'says nothing about whether PWL is needed for FEASIBILITY -- and that argument is\n' ...
    'independent and stronger. Without the fill-order binaries the LP relaxation reports\n' ...
    'dispatches the machines cannot physically produce, at every price and in every\n' ...
    'season, which is a correctness failure rather than a cost one. The heat pump''s\n' ...
    'slopes are non-monotonic too (segment 2 above segment 1), so it needs those\n' ...
    'binaries for the same reason the moment its curve is modelled at all.\n']);

end
