function mc_report_month4i(S)
%MC_REPORT_MONTH4I Statistics and verdicts for the Month 4i heat-pump gate.
%   INTERNAL REPORTER, not a script -- call mc_aggregate('month4i') instead.
%
%   Extracted VERBATIM from main_month4i_heatpump_pwl_gate.m so the
%   single-process path and the chunked path print identical output BY
%   CONSTRUCTION rather than by two implementations agreeing. Takes a struct
%   of raw per-draw vectors; statistics are never combined across chunks.

    %% NOT A SCRIPT. Running this bare gives a cryptic undefined-variable error,
    %% so it says so itself instead.
    if nargin < 1
        error('mc_report_month4i:notAScript', ...
              ['mc_report_month4i is an INTERNAL REPORTER, not a script.\n' ...
               'Run  mc_aggregate(''month4i'')  to print the report from saved chunk\n' ...
               'files, or run  main_month4i_heatpump_pwl_gate  directly.']);
    end

    thisFile = mfilename('fullpath');
    addpath(fileparts(thisFile));
    addpath(fullfile(fileparts(thisFile), '..', 'month3_multiscale_optimization'));
    p = S.p; nDraw = S.nDraw; seasons = S.seasons; drawSeason = S.drawSeason;
    hpRef = S.hpRef; pPWL = S.pPWL; pChord = S.pChord;
    pCurv = S.pCurv; pLegacy = S.pLegacy; optFull = S.optFull;
    dGate = S.dGate;
    dCurv = S.dCurv;
    dLegacy = S.dLegacy;
    uMedian = S.uMedian;
    errPWL = S.errPWL;
    errChord = S.errChord;
    errCurv = S.errCurv;
    tPWL = S.tPWL;
    tChord = S.tChord;
    hpElecPWL = S.hpElecPWL;
    hpElecChord = S.hpElecChord;
    corrPWL = S.corrPWL;
    corrChord = S.corrChord;

%% (A) The gate ----------------------------------------------------------
stGate = paired_stats(dGate, true);
fprintf('\n=====================================================\n');
fprintf(' (A) THE GATE: %d-segment PWL vs 1-segment chord of the same curve\n', p.HeatPump.nSegments);
fprintf('=====================================================\n');
fprintf('%-22s %8s %8s %8s %18s %18s %8s %9s\n', '', 'mean %', 'median', 'sd', ...
    '95% CI (t)', '95% CI (boot)', 'sign+', 'sign p');
fprintf('%-22s %8.3f %8.3f %8.3f [%+8.3f,%+7.3f] [%+8.3f,%+7.3f] %4d/%-3d %9.2g\n', ...
    'Benefit of HP PWL', stGate.mean, stGate.median, stGate.sd, ...
    stGate.ciLo, stGate.ciHi, stGate.bootLo, stGate.bootHi, ...
    stGate.nAgree, stGate.nNonZero, stGate.signP);
fprintf('\nVerdict: %s\n', stGate.verdict);

fprintf('\n--- Per season ---\n');
fprintf('%-10s %9s %9s %18s %8s   %s\n', 'season', 'mean %', 'median', '95% CI (t)', 'sign+', 'verdict');
stSea = cell(1, numel(seasons));
for sIdx = 1:numel(seasons)
    sel = strcmp(drawSeason, seasons{sIdx});
    stSea{sIdx} = paired_stats(dGate(sel), true);
    st = stSea{sIdx};
    fprintf('%-10s %9.3f %9.3f [%+8.3f,%+7.3f] %4d/%-3d   %s\n', seasons{sIdx}, ...
        st.mean, st.median, st.ciLo, st.ciHi, st.nAgree, st.nNonZero, st.verdict);
end

%% WHY: where on the curve the heat pump actually lives ------------------
% The pooled null and the seasonal split only make sense together with this,
% so it is measured rather than reasoned about.
fprintf('\n--- WHY the sign flips: where the heat pump operates, and how wrong each model is there ---\n');
fprintf('%-10s %14s %12s %14s %14s %14s\n', 'season', 'median load u', 'frac in seg1', ...
    'PWL err (kW)', 'chord err (kW)', 'curv err (kW)');
for sIdx = 1:numel(seasons)
    sel = strcmp(drawSeason, seasons{sIdx});
    fcS = forecast_profiles(42, 1.0, [], seasons{sIdx});
    RS  = simulate_multiscale_day(pPWL, fcS, optFull);
    uR  = RS.Php5(RS.Php5 > 1e-6) / p.HeatPump.Pmax;
    if isempty(uR); fracSeg1 = 0; else; fracSeg1 = mean(uR < 1/p.HeatPump.nSegments); end
    fprintf('%-10s %14.3f %12.2f %+14.3f %+14.3f %+14.3f\n', seasons{sIdx}, ...
        mean(uMedian(sel)), fracSeg1, mean(errPWL(sel)), mean(errChord(sel)), mean(errCurv(sel)));
end
fprintf(['\n(+ = the model OVER-PROMISES heat. This project already established for the fuel\n' ...
    ' cell that optimism and pessimism are not symmetric in cost -- a shortfall is covered\n' ...
    ' at the import tariff while a surplus is only worth the export price -- so the SIGN\n' ...
    ' of this column predicts the sign of the cost penalty.)\n']);

fprintf(['\nTHE MECHANISM, AND IT IS A BREAKPOINT-PLACEMENT PROBLEM RATHER THAN A PWL ONE.\n' ...
    'In winter the heat pump runs near its rating and crosses every segment, so a\n' ...
    '5-segment model is far more accurate than a chord and PWL pays. In summer the only\n' ...
    'heat demand is a flat domestic-hot-water baseline, the heat pump sits at about 13%%\n' ...
    'load, and it therefore lives almost entirely INSIDE SEGMENT 1 -- where a uniform\n' ...
    '5-segment fit averages the curve''s steepest rise into one wide chord of slope %.2f\n' ...
    'against a true COP near %.2f at that load. The finer model is the MORE optimistic one\n' ...
    'exactly where the device operates, and optimism costs money.\n' ...
    '\nSo the failure is not "PWL does not help a heat pump". It is "uniform breakpoints put\n' ...
    'the coarsest approximation exactly where this curve bends most, and a device that\n' ...
    'operates only in that region is worse off with them than without them."\n'], ...
    hpRef.slopes(1), hpRef.copRated * p.HeatPump.partLoad_func(0.13));

%% The placement fix, measured -------------------------------------------
stCurv = paired_stats(dCurv, true);
hpCurvRef = heatpump_curve(pCurv, 9.0);
fprintf('\n--- Same test with CURVATURE-PLACED breakpoints (same segment count) ---\n');
fprintf('breakpoints at u = '); fprintf('%.3f ', hpCurvRef.bkpt.x / p.HeatPump.Pmax); fprintf('\n');
fprintf('slopes           = '); fprintf('%.3f ', hpCurvRef.slopes); fprintf('\n');
fprintf('binaries still required? %d\n', hpCurvRef.needsBinaries);
fprintf('%-22s %8.3f %8.3f %8.3f [%+8.3f,%+7.3f] %4d/%-3d %9.2g\n', 'Benefit vs chord', ...
    stCurv.mean, stCurv.median, stCurv.sd, stCurv.ciLo, stCurv.ciHi, ...
    stCurv.nAgree, stCurv.nNonZero, stCurv.signP);
fprintf('Verdict: %s\n', stCurv.verdict);
fprintf('%-10s %9s %18s   %s\n', 'season', 'mean %', '95% CI (t)', 'verdict');
for sIdx = 1:numel(seasons)
    sel = strcmp(drawSeason, seasons{sIdx});
    stc = paired_stats(dCurv(sel), true);
    fprintf('%-10s %9.3f [%+8.3f,%+7.3f]   %s\n', seasons{sIdx}, stc.mean, stc.ciLo, stc.ciHi, stc.verdict);
end

%% The cost of the complexity -------------------------------------------
nBinPWL = (p.HeatPump.nSegments - 1) * 24;
fprintf('\n--- What the complexity costs ---\n');
fprintf('%-40s %12.3f s\n', 'Mean closed-loop solve time, PWL',   mean(tPWL));
fprintf('%-40s %12.3f s\n', 'Mean closed-loop solve time, chord', mean(tChord));
fprintf('%-40s %+11.1f %%\n', 'Added solve time', 100*(mean(tPWL)-mean(tChord))/mean(tChord));
fprintf('%-40s %12d\n', 'Added binaries, day-ahead (24 h)', nBinPWL);
fprintf('%-40s %12d\n', 'Added binaries, per intraday solve', (p.HeatPump.nSegments-1)*4);
fprintf('%-40s %12.1f kWh\n', 'Mean HP electricity, PWL',   mean(hpElecPWL));
fprintf('%-40s %12.1f kWh\n', 'Mean HP electricity, chord', mean(hpElecChord));
fprintf('%-40s %12.2f $\n', 'Mean true-curve correction, PWL',   mean(corrPWL));
fprintf('%-40s %12.2f $\n', 'Mean true-curve correction, chord', mean(corrChord));

%% (B) Context: the curve vs the legacy constant -------------------------
stLeg = paired_stats(dLegacy, true);
fprintf('\n=====================================================\n');
fprintf(' (B) CONTEXT, NOT THE GATE: the curve vs the legacy constant COP 3.2\n');
fprintf('=====================================================\n');
fprintf('mean %+.2f%%, median %+.2f%%, 95%% CI [%+.2f, %+.2f], %d/%d draws\n', ...
    stLeg.mean, stLeg.median, stLeg.ciLo, stLeg.ciHi, stLeg.nAgree, stLeg.nNonZero);
fprintf(['\nThis is a LEVEL change and not a PWL result. The legacy model assumed COP 3.2\n' ...
    'everywhere; the sourced curve gives %.2f at the shoulder rating point and %.2f in\n' ...
    'winter. A better heat pump is cheaper to run -- that is arithmetic, not modelling,\n' ...
    'and quoting it as a PWL benefit would be the same category error this project\n' ...
    'already refuses for the 72.1%% headline. It is reported because the seasonal cost\n' ...
    'figures in Month 3 and Month 4a move by this much, not because it argues for PWL.\n'], ...
    heatpump_curve(p, 9.0).copRated, heatpump_curve(p, 0.5).copRated);

%% Verdict ---------------------------------------------------------------
fprintf('\n=====================================================\n');
fprintf(' GATE DECISION\n');
fprintf('=====================================================\n');
passed = stGate.distinguishable && stGate.bootDistinguishable && stGate.signSignificant && stGate.mean > 0;
curvPassed = stCurv.distinguishable && stCurv.bootDistinguishable && stCurv.signSignificant && stCurv.mean > 0;

if passed
    fprintf(['GATE PASSED. Heat-pump PWL is worth %+.3f%% (95%% CI %+.3f to %+.3f), the\n' ...
        'direction held in %d of %d draws, and the exact sign test gives p = %.2g.\n'], ...
        stGate.mean, stGate.ciLo, stGate.ciHi, stGate.nAgree, stGate.nNonZero, stGate.signP);
else
    fprintf(['*** THE GATE AS SPECIFIED DOES NOT PASS. ***\n' ...
        'Heat-pump PWL with UNIFORM breakpoints -- the same treatment the fuel cell gets --\n' ...
        'measures %+.3f%% over %d draws, 95%% CI [%+.3f, %+.3f], which SPANS ZERO. It costs\n' ...
        '%d extra binaries per day-ahead solve and %+.0f%% closed-loop solve time for a\n' ...
        'benefit that cannot be resolved.\n' ...
        '\nPer the instructions, Tasks 2 (PV inverter) and 3 (battery) were therefore NOT\n' ...
        'run. More PWL is not assumed to be better.\n' ...
        '\nAND THE DEVICE-LEVEL VERDICT WOULD BE THE WRONG LESSON TO TAKE. The seasonal\n' ...
        'split resolves cleanly in every season and does not agree with itself: %+.3f%% in\n' ...
        'winter and %+.3f%% at the shoulder, both distinguishable from zero, against\n' ...
        '%+.3f%% in summer, which is a RELIABLE COST (0 of 20 draws in the claimed\n' ...
        'direction). The pooled null is those cancelling, not an absence of effect.\n'], ...
        stGate.mean, stGate.n, stGate.ciLo, stGate.ciHi, nBinPWL, ...
        100*(mean(tPWL)-mean(tChord))/mean(tChord), ...
        stSea{1}.mean, stSea{2}.mean, stSea{3}.mean);
end

if curvPassed
    fprintf(['\n--- AND THE SAME CURVE WITH BREAKPOINTS IN BETTER PLACES DOES PASS ---\n' ...
        'Curvature-placed breakpoints, SAME segment count, SAME binaries, same solve cost:\n' ...
        '%+.3f%% (95%% CI %+.3f to %+.3f), %d of %d draws, sign test p = %.2g. All three\n' ...
        'tests agree, and summer stops being a cost (%+.3f%%, no longer resolvable as\n' ...
        'negative) instead of remaining one.\n' ...
        '\nSO THE HONEST CONCLUSION IS NOT "PWL DOES NOT HELP A HEAT PUMP". It is:\n' ...
        '  Uniform breakpoints put the coarsest part of the fit exactly where this curve\n' ...
        '  bends most, and a device that operates only in that region is worse off with\n' ...
        '  them than without them. Placement, not segment count, is what was wrong.\n' ...
        '\nWHY THE DEFAULT IS STILL OFF, stated because passing a gate and shipping a\n' ...
        'change are different decisions. The configuration that passes is not the one the\n' ...
        'gate specified, it was measured after the fact on the same draws that diagnosed\n' ...
        'the failure, and enabling it would also apply the +%.0f%% LEVEL change in section\n' ...
        '(B) to every cost figure in Months 3 and 4. multiscale_default_params.m therefore\n' ...
        'keeps the legacy constant so every existing result reproduces exactly, and this\n' ...
        'file records what a follow-up session should enable and what it would be worth.\n' ...
        'Confirming a fix on the data that suggested it is a weaker claim than the one\n' ...
        'this project usually makes, and it is labelled rather than promoted.\n'], ...
        stCurv.mean, stCurv.ciLo, stCurv.ciHi, stCurv.nAgree, stCurv.nNonZero, stCurv.signP, ...
        paired_stats(dCurv(strcmp(drawSeason,'summer')), true).mean, stLeg.mean);
else
    stCurvSum = paired_stats(dCurv(strcmp(drawSeason,'summer')), true);
    fprintf(['\nCURVATURE PLACEMENT DOES NOT RESCUE IT EITHER (%+.3f%%, 95%% CI [%+.3f, %+.3f]),\n' ...
        'so the negative is about the device rather than about where the breakpoints sit.\n' ...
        '\nAND THAT IS A REVERSAL WORTH STATING PLAINLY, because an earlier version of this\n' ...
        'study reported curvature placement as the fix that turned the gate positive. It was\n' ...
        'measured with a defective cost correction (see true_curve_cost.m, the covering-COP\n' ...
        'defect, which fell almost entirely on summer). Corrected, the claim does not hold.\n' ...
        '\nWHAT DID NOT CHANGE is the APPROXIMATION side: curvature placement still cuts the\n' ...
        'low-load over-promise, from %+.3f kW to %+.3f kW in summer, moving the error to the\n' ...
        'pessimistic side. So it genuinely is the better FIT and still the worse COST\n' ...
        '(summer %+.3f%%). Those two things coming apart is the useful result: a fit that is\n' ...
        'closer to the true curve does not automatically buy a cheaper dispatch, and any\n' ...
        'argument for PWL that reasons from approximation error alone is incomplete.\n' ...
        '\nONE BOUND ON THAT COMPARISON, stated because it cuts toward this conclusion. The\n' ...
        'correction credits surplus heat at the same COP at which it charges a shortfall, so\n' ...
        'a systematically PESSIMISTIC fit earns a systematic credit. The chord is the most\n' ...
        'pessimistic model here and it wins in summer; part of that margin is the convention\n' ...
        'rather than the physics. It is left as measured rather than re-tuned, because\n' ...
        'adjusting the convention after seeing which arm it favours is exactly the move this\n' ...
        'session is meant to avoid. The GATE verdict does not depend on it -- the gate spans\n' ...
        'zero under BOTH the defective and the corrected convention.\n'], ...
        stCurv.mean, stCurv.ciLo, stCurv.ciHi, ...
        mean(errPWL(strcmp(drawSeason,'summer'))), mean(errCurv(strcmp(drawSeason,'summer'))), ...
        stCurvSum.mean);
end

hpThruMean = mean(hpElecPWL);
fcSlG  = diff(p.PWL.bkpt_e.y) ./ diff(p.PWL.bkpt_e.x);
fcCurvG = (max(fcSlG)-min(fcSlG))/mean(fcSlG);
hpCurvG = (max(hpRef.slopes)-min(hpRef.slopes))/mean(hpRef.slopes);
fprintf(['\nWHAT THIS BOUNDS, AND IT IS THE POINT OF THE SESSION. The heat pump moves\n' ...
    '%.0f kWh/day of electricity here against the fuel cell''s few dozen kWh of hydrogen at\n' ...
    'today''s delivered price -- roughly 8x more, measured on a common basis in\n' ...
    'main_month4j -- so a rule of the form "PWL pays above X kWh/day throughput" would\n' ...
    'have predicted a clear win here and did not get one. Throughput is necessary and\n' ...
    'nowhere near sufficient.\n' ...
    '\nIts curvature is NOT comparable to the fuel cell''s, and an earlier version of this\n' ...
    'file said it was: %.2f against %.2f, i.e. %.1fx FLATTER. That weakens the "biggest\n' ...
    'device first" intuition further rather than rescuing it -- the heat pump wins on\n' ...
    'throughput and loses on curvature, and it still does not resolve. See main_month4j\n' ...
    'for whether the PRODUCT of the two predicts anything (it does not order the cells).\n'], ...
    hpThruMean, hpCurvG, fcCurvG, fcCurvG/max(hpCurvG,1e-9));

end
